In [175]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem.PandasTools import LoadSDF
import tmap as tm
from map4 import MAP4Calculator
import warnings, json, traceback, csv
import pickle
from progress_bar import print_progress_bar
warnings.filterwarnings('ignore')

In [6]:
def pickle_dump(file_name, data):
    with open(file_name, 'wb') as f:
        pickle.dump(data, f)
def pickle_load(file_name):
    with open(file_name, 'rb') as f:
        return pickle.load(f)

In [3]:
DATA_FOLDER = 'database_unification_data/'

In [37]:
def fp_similarity_indiv(df_to_test, id_to_test_column_name, df_ids, id_column_name):
    '''
    Function that compares compound fingerprints and gets the distance between each of them.
    If the distance is 1, the compound database id is added to the ids dataframe. If there are no compounds with distance 1,
    the compound is appended to the ids dataframe.
    '''
    dim = 1024
    MAP4 = MAP4Calculator(dimensions=dim)
    ENC = tm.Minhash(dim)

    df_test = df_to_test.copy()
    df_total = df_ids.copy()

    print_progress_bar(0, len(df_test), suffix=f'(0/{len(df_test)})')
    for i in range(len(df_test)):
        try:
            current_fp = MAP4.calculate(df_test.iloc[i]['Molecule'])
        except Exception as e1:
            current_fp = None
            print(f'Error calculating fp for compound {i} in dataframe to test:\n{str(e1)}')
        found = False
        if current_fp:
            for j in range(len(df_total)):
                try:
                    compared_fp = MAP4.calculate(df_total.iloc[j]['Molecule'])
                except Exception as e2:
                    compared_fp = None
                    print(f'Error calculating fp for compound {j} in ids dataframe:\n{str(e2)}')
                if compared_fp:
                    current_distance = ENC.get_distance(current_fp, compared_fp)
                    if current_distance == 0:
                        df_ids.iloc[j][id_column_name] = df_to_test.iloc[i][id_to_test_column_name]
                        found = True
                        break
            if not found:
                new_df_row = {'ID': len(df_ids), id_column_name: df_test.iloc[i][id_to_test_column_name], 'Molecule': df_test.iloc[i]['Molecule'], 'SMILES': df_test.iloc[i]['SMILES']}
                df_ids = df_ids.append(new_df_row, ignore_index=True)
        print_progress_bar(i + 1, len(df_test), suffix=f'({i}/{len(df_test)})')
    
    return df_ids

In [156]:
# Load the BUL (Biological unit library) or Natural products library
with open('data/BUL_names.pkl', 'rb') as f:
    BULnames = pickle.load(f)

In [157]:
BUL_ids = list(set(list(sum(BULnames.keys(), ()))))

In [158]:
len(BUL_ids)

21057

In [153]:
BUL_ids

['C13750',
 'C20798',
 'C06007',
 'C06099',
 'C16207',
 'C10719',
 'C10586',
 'C07837',
 'C11169',
 'C00437',
 'C21594',
 '134812127_mod_0',
 'C02656_mod_2',
 'C22102',
 'C22141',
 'C01015',
 'C10708',
 'C15117',
 'C12115',
 'C00771',
 'C08885',
 'C10093',
 'C06033',
 'C04081',
 'C21923',
 'C12344',
 'C03843',
 'C15902',
 'C15996',
 'C17747',
 'C19828',
 'C18035',
 'C15579',
 'C10558',
 'C14937',
 'C13103',
 '162985355_mod_0',
 'C07006',
 'C11133',
 'C10350',
 'C20331',
 'C18642',
 'C04615',
 'C14731',
 'C02821',
 'C19409',
 'C00725',
 'C00025_mod_0',
 'C08759',
 '146682617_mod_0',
 '162962840_mod_0',
 'C16526',
 'C15137',
 '78383960',
 '146682760_mod_99',
 'C14577',
 'C17146',
 'C20248',
 'C13591',
 'C09326',
 '5282597',
 'C09333',
 'C01590',
 'C02457',
 'C08580',
 'C20815',
 'C17827',
 'C17497',
 '146683552_mod_82',
 'C07381',
 'C04644',
 'C14573',
 'C11881',
 '163030178_mod_0',
 '146682760_mod_97',
 'C20947',
 'C18988',
 '5312644_mod_0',
 'C01270',
 'C01279',
 'C18545',
 'C17722',
 'C21580',
 '138454203_mod_0',
 'C14634',
 '135002_mod_0',
 'C19242',
 'C17107',
 '23250',
 'C09029',
 'C18500',
 'C00250',
 'C15373',
 'C14933',
 'C15168',
 '11463588',
 'C11360',
 '146682758_mod_26',
 'C21107',
 'C19164',
 'C07034',
 'C21772',
 'C19482',
 'C01991',
 '73242171_mod_0',
 'C10628',
 'C17837',
 '146682758',
 'C11015',
 'C17826',
 '146683550_mod_13',
 'C20365',
 'C00248',
 'C02999',
 'C19539',
 'C18019',
 'C09772',
 'C22200',
 '75201659',
 '14427323',
 'C14043',
 'C01875',
 'C21569',
 'C19047',
 'C11844',
 'C21517',
 'C15203',
 'C07996',
 'C20624',
 'C04713',
 '18676629_mod_3',
 'C08518',
 'C07711',
 'C15695',
 'C10139',
 'C18568',
 'C00079_mod_0',
 'C09916',
 '52921744',
 'C17775',
 'C09753',
 'C13415',
 'C17362',
 'C22012',
 '146682621_mod_6',
 'C08112',
 'C18574',
 'C13858',
 'C01455',
 'C13832',
 'C10912',
 'C10519',
 '52921860',
 '10982228',
 'C20983',
 '53813767',
 'C11584',
 'C00265',
 '74611',
 'C12096',
 'C19991',
 'C05579',
 '95300',
 'C10027',
 'C11265',
 'C00823',
 'C15605',
 'C03764',
 'C05574',
 'C00586',
 'C17382',
 '123364114',
 'C19943',
 '24786700',
 'C02066',
 '5282938_mod_0',
 'C02389',
 'C11809',
 'C08784',
 'C15293',
 'C08376',
 'C21044',
 'C20717',
 'C12640',
 '5282610_mod_0',
 'C05638',
 'C20994',
 '151922',
 'C05370',
 'C12284',
 'C20010',
 'C01146_mod_0',
 'C06425',
 'C15626',
 'C14671',
 'C07155',
 'C15046',
 'C12307',
 '399_mod_5',
 'C20790',
 '5312334_mod_0',
 'C09632',
 '76863_mod_0',
 '162875369_mod_1',
 'C10819',
 'C03654',
 'C07389',
 'C09021',
 'C17960',
 'C06584',
 '146683552_mod_89',
 'C14446',
 '5288377',
 'C11704',
 'C16972',
 'C06825',
 'C20379',
 'C03090',
 'C13494',
 '138454173_mod_0',
 '5312648_mod_0',
 'C17424',
 'C11476',
 'C01133',
 'C12424',
 'C15720',
 'C09739',
 '163064282_mod_0',
 'C08624',
 'C04265',
 'C08865',
 'C00691',
 '5312921_mod_0',
 'C09670',
 'C03943',
 'C00989',
 'C19269',
 'C00431',
 'C13697',
 '129726852_mod_0',
 'C20456',
 '138454204',
 '2724554_mod_2',
 'C19783',
 'C09181',
 'C05803',
 'C07966',
 '18676629_mod_2',
 'C10031',
 'C11946',
 'C18070',
 'C01620',
 'C04527',
 'C17524',
 'C12302',
 '5469810',
 'C01048',
 'C06239',
 'C21578',
 'C08233',
 'C19878',
 '146682760_mod_36',
 '76518481_mod_0',
 '71402234_mod_0',
 '73721023_mod_0',
 'C19362',
 'C19666',
 'C21613',
 'C08490',
 'C18410',
 'C21423',
 'C07612',
 '75009',
 'C01144',
 'C01438',
 'C11954',
 'C19059',
 'C19535',
 'C02957',
 'C06940',
 'C08968',
 'C10287',
 'C08833',
 'C05435',
 'C11988',
 'C08555',
 '309_mod_7',
 'C05706',
 'C15849',
 'C20910',
 'C11507',
 'C11942',
 '10424556',
 'C01410',
 'C19916',
 'C10460',
 'C11060',
 'C10107',
 'C07254',
 'C08973',
 'C04535',
 'C12197',
 'C11702',
 'C14637',
 'C01157_mod_0',
 'C20311',
 'C08265',
 '5282787',
 'C12155',
 'C08570',
 'C17343',
 'C13813',
 '162900451_mod_2',
 'C09715',
 'C09784',
 'C06599',
 'C05519',
 '146683550_mod_0',
 'C10210',
 'C21849',
 'C19337',
 'C03830',
 'C10046',
 'C14513',
 'C14971',
 'C09498',
 'C11232',
 'C14092',
 '3632876',
 'C21217',
 '146683552_mod_94',
 'C22024',
 'C14377',
 'C16737',
 'C00208',
 'C10118',
 '5312578',
 '20848956',
 'C16196',
 'C05800',
 'C16488',
 'C18719',
 'C14352',
 'C17551',
 'C05695',
 'C22090',
 'C10954',
 '56935808_mod_0',
 'C20844',
 'C02578',
 'C02628',
 'C17902',
 '11701_mod_3',
 'C09235',
 'C00185',
 'C19260',
 'C09914',
 'C09103',
 '549854',
 'C02264',
 'C20152',
 'C18526',
 'C07138',
 'C09051',
 'C01566',
 'C10524',
 '162911315',
 '154212_mod_0',
 'C02539',
 'C11999',
 '162867002',
 'C14957',
 '162927483',
 '85699046',
 'C07868',
 'C20962',
 'C07336',
 'C06564',
 'C17778',
 'C14411',
 'C06360',
 'C15178',
 'C18094',
 'C01009',
 'C17868',
 'C11740',
 'C07323',
 'C06427_mod_0',
 'C08751',
 'C11685',
 'C20679',
 '182089',
 'C07010',
 'C10814',
 'C18787',
 'C19211',
 'C16771',
 'C08450',
 'C07919',
 'C11305',
 'C20082',
 'C15877',
 'C02778',
 'C06734',
 'C21353',
 'C15360',
 'C11422',
 '12575964',
 'C00417_mod_10',
 'C16971',
 'C14382',
 'C00705',
 'C13086',
 'C15128',
 '5282814_mod_0',
 'C16402',
 'C10057',
 'C18499',
 'C14369',
 'C17869',
 'C20189',
 'C18986',
 'C17384',
 'C19369',
 'C08605',
 'C18987',
 'C19890',
 'C11689',
 '57494716_mod_0',
 'C16855',
 'C12327',
 'C14058',
 'C15379',
 'C19415',
 '78360',
 '51439649_mod_10',
 'C10522',
 'C02370',
 'C01951',
 'C00049_mod_1',
 'C20506',
 'C11118',
 'C18091',
 'C03998',
 'C18671',
 '118343040_mod_2',
 '70_mod_0',
 'C18226',
 'C21301',
 'C09218',
 'C19082',
 'C03969',
 '5287609_mod_4',
 'C06184',
 'C20460',
 'C15329',
 'C14493',
 'C21248',
 '73856880',
 'C08969',
 'C10357',
 'C11583',
 '5312669_mod_0',
 'C00445',
 'C14841',
 'C00366',
 'C04746',
 'C01092',
 'C02363',
 'C11202',
 'C01210',
 'C15342',
 'C11502',
 'C00158_mod_1',
 'C17891',
 '129716173',
 '155301_mod_0',
 'C08509',
 'C16552',
 'C00158_mod_14',
 'C15583',
 'C01404',
 'C02718',
 'C20453',
 'C05376',
 '5282457',
 'C09497',
 'C09459',
 'C17394',
 'C03743',
 'C17578',
 'C08831',
 'C18852',
 'C09499',
 'C03629',
 'C11849',
 'C17585',
 'C04300',
 'C18458',
 'C16744',
 'C16556',
 'C07538',
 'C07836',
 'C10319',
 'C17003',
 'C10052',
 'C12317',
 '163057816',
 '53262386',
 'C00110',
 'C10003',
 'C10077',
 'C11707',
 '5282650',
 'C17543',
 'C05434',
 'C14520',
 '44203444_mod_0',
 'C11100',
 'C07125',
 'C00371',
 'C03539',
 '146683552_mod_103',
 'C05802',
 'C03979',
 'C08766',
 'C21057',
 'C16476',
 'C14854',
 'C16954',
 'C19617',
 'C10527',
 'C13827',
 'C20386',
 '5282916_mod_0',
 'C07367',
 '11036420_mod_0',
 'C03927',
 'C16931',
 'C01514',
 'C03981',
 'C08569',
 '163088984',
 'C22028',
 'C17491',
 'C21082',
 'C09692',
 'C11308',
 'C22293',
 'C16430',
 'C00158_mod_12',
 '56839943',
 'C17730',
 'C10168',
 'C16353',
 '22371595_mod_0',
 'C04559',
 'C05472',
 'C13766',
 '52919352_mod_0',
 'C01746',
 'C11663',
 'C14496',
 'C03963',
 'C06860',
 '75009_mod_0',
 'C14950',
 'C16570',
 'C05520',
 'C15508',
 'C15103',
 '5312427',
 'C19695',
 'C10765',
 'C09548',
 'C16781',
 'C13355',
 'C16597',
 'C01691',
 'C09806',
 'C06654',
 'C06268',
 'C00408_mod_0',
 'C00944',
 'C12366',
 'C19762',
 '5312781',
 'C08723',
 '96020391_mod_1',
 'C06893',
 'C20477',
 'C21441',
 '6439582',
 'C05011',
 'C06477_mod_0',
 'C06970',
 'C05261',
 'C15188',
 'C03051',
 'C04608',
 'C07771',
 'C17416',
 'C15753',
 'C16783',
 '145721311_mod_0',
 'C09055',
 'C16831',
 '138454199',
 '53921228_mod_0',
 'C08898',
 'C16652_mod_0',
 'C19339',
 'C18869',
 'C19385',
 'C15036',
 'C17418',
 'C22013',
 'C20135',
 'C05575',
 '162985202',
 'C13364',
 'C05616_mod_0',
 'C17973',
 'C17104',
 'C12433',
 'C21768',
 'C09513',
 'C02627',
 '76312534_mod_0',
 'C08278',
 'C05516',
 'C22055',
 'C11160',
 'C15560',
 '53262345',
 'C10573',
 'C17971',
 'C00552',
 'C08114',
 'C21017',
 'C02856',
 '5282808',
 'C08602',
 '3084276_mod_0',
 'C08350',
 'C06167',
 'C20217',
 'C05291',
 'C03671',
 '5282595',
 '51439649_mod_13',
 'C11116',
 'C01114',
 'C13843',
 'C18735',
 'C10058',
 '129819530_mod_0',
 'C16318',
 'C09375',
 '15157102_mod_0',
 'C14621',
 'C08392',
 'C18448',
 'C20806',
 'C21265',
 'C07376',
 '5287609_mod_13',
 'C06327',
 'C11084',
 '146683551_mod_103',
 'C02549',
 'C13738',
 'C20516',
 'C08211',
 'C09852',
 'C11288',
 'C11322',
 '146682760_mod_19',
 'C07817',
 'C12409',
 '5282172',
 'C05339',
 'C18906',
 'C17663',
 'C15139',
 'C15426',
 'C08179',
 '91169_mod_0',
 'C18809',
 'C19942',
 '163020806',
 'C09256',
 '146683551_mod_107',
 '12235236_mod_0',
 'C04318',
 'C17239',
 'C20124',
 'C10617',
 '5280595_mod_0',
 'C09777',
 'C06025_mod_27',
 'C15696',
 'C20700',
 'C06315',
 'C18819',
 'C15684',
 '56633806',
 'C01784',
 'C02029',
 'C05847',
 '146682758_mod_94',
 'C11863',
 'C16610',
 'C00302',
 'C21144',
 'C07423',
 'C22164',
 '145720652_mod_0',
 'C12141',
 'C15687',
 'C15942',
 'C21148',
 'C17230',
 'C00894',
 'C14497',
 '162934221',
 'C19152',
 'C00011',
 'C06763',
 'C17496',
 'C15047',
 'C05811',
 'C22247',
 'C10575',
 '162979714',
 'C22029',
 'C15147',
 'C20174',
 '971_mod_0',
 '5282773',
 'C18193',
 'C08888',
 '15569776_mod_0',
 '3035421',
 'C03677',
 'C16593',
 'C09141',
 'C06689',
 'C13748',
 'C00283',
 '146683552_mod_109',
 'C01230',
 'C19479',
 'C17527',
 'C18791',
 'C20954',
 'C22066',
 'C22173',
 'C02338',
 'C06648',
 'C11131',
 'C17610',
 'C07093',
 'C03070',
 'C14704',
 'C15737',
 'C18108',
 'C15688',
 'C18030',
 '5282602_mod_0',
 '5282767_mod_0',
 '195555',
 'C14944',
 'C10084',
 'C21320',
 '163106171_mod_0',
 'C10590',
 '5282596',
 'C20122',
 'C06723',
 'C19120',
 'C17616',
 '5282875',
 'C15552',
 'C06952',
 'C20609',
 'C16216',
 'C09354',
 'C09208',
 'C10300',
 'C14710',
 'C15415',
 'C19103',
 'C02197',
 'C15245',
 '5470168',
 'C14853',
 'C05382',
 'C16648',
 'C02890',
 'C08302',
 'C06108',
 'C11030',
 'C21354',
 'C10897',
 'C20131',
 'C10996',
 'C17977',
 'C09057',
 'C14919',
 'C14643',
 '12593478',
 '44256492',
 'C08521',
 'C20270',
 'C01037',
 'C01102',
 'C15719',
 'C09179',
 '146683552_mod_69',
 '23427391',
 'C21591',
 '102074921_mod_0',
 'C20050',
 'C00479',
 'C02272',
 '5281932',
 'C05464',
 'C10069',
 'C05131',
 '44176401_mod_0',
 'C11282',
 'C17582',
 'C17805',
 'C00402_mod_2',
 '5312640_mod_0',
 'C15617',
 'C11388',
 'C20484',
 'C20344',
 'C22291',
 'C17707',
 'C19619',
 'C18942',
 'C08289',
 'C14990',
 'C06354',
 '138454216',
 'C09261',
 'C21401',
 '52921746',
 'C15992',
 'C11144',
 'C03646',
 'C01961',
 'C18800',
 'C09581',
 'C07827',
 '71338159',
 'C16491',
 'C02835',
 '5312691_mod_0',
 'C04259',
 'C01594',
 'C05643',
 'C09517',
 'C17422',
 '14376443',
 'C04932',
 'C08103',
 'C13836',
 '162953603_mod_0',
 'C04628',
 'C19378',
 'C05385',
 '236484_mod_0',
 'C00386',
 'C14555',
 'C03037',
 'C07026',
 'C17914',
 'C09813',
 'C17056',
 'C20618',
 'C00170',
 'C01267',
 'C10076',
 'C10391',
 'C14181',
 'C08278_mod_3',
 'C11293',
 'C08277_mod_2',
 '15160959_mod_0',
 '139584015_mod_0',
 '139065_mod_0',
 'C17127',
 'C20158',
 'C09680',
 '57494716',
 'C04282',
 'C18552',
 'C19432',
 '146682760_mod_3',
 'C19487',
 'C05086',
 'C10337',
 '139583621_mod_0',
 '162920802_mod_0',
 'C07909',
 'C15028',
 '6506600',
 'C15895',
 'C14506',
 'C07092',
 'C12406',
 'C14746',
 'C05773',
 'C00973',
 'C17967',
 'C15328',
 'C15516',
 'C07001',
 'C01346',
 'C21961',
 'C04663',
 'C09128',
 'C18740',
 'C01424_mod_0',
 'C09675',
 'C17894',
 'C05163',
 '10924449',
 'C05601_mod_3',
 '5790536_mod_1',
 '52921811_mod_0',
 'C17465',
 'C22085',
 'C14766',
 'C08275',
 'C06748',
 'C15783',
 'C13798',
 'C18237',
 'C17749',
 'C09727',
 '5312568_mod_0',
 'C01732_mod_1',
 'C05551',
 'C10136',
 'C22190',
 'C01621',
 'C14132',
 'C19096',
 'C11687',
 'C04064',
 'C19713',
 'C18755',
 'C19899',
 'C06981',
 'C07235',
 'C10445',
 'C00023',
 '5282750',
 'C16996',
 '14211733',
 'C18753',
 'C14299',
 'C13629',
 'C00795',
 'C19536',
 'C06902',
 'C02037',
 'C09112',
 'C01467',
 'C16667',
 '71442740_mod_0',
 'C10950',
 'C09805',
 '92033282',
 'C18794',
 'C08514',
 '52921869_mod_2',
 'C17210',
 'C14539',
 '162970135',
 'C11800',
 'C16374',
 '10660115',
 'C22290',
 'C22092',
 'C06721',
 'C16612',
 'C16930',
 'C06852',
 'C09299',
 '439766_mod_2',
 'C10390',
 'C11483',
 '10924204_mod_0',
 'C14970',
 ...]

In [159]:
BUL_ids_filtered = [id for id in BUL_ids if id.startswith('C')]

In [169]:
BUL_cids = [id for id in BUL_ids if not id.startswith('C')]

In [170]:
BUL_cids

['134812127_mod_0',
 '162985355_mod_0',
 '146682617_mod_0',
 '162962840_mod_0',
 '78383960',
 '146682760_mod_99',
 '5282597',
 '146683552_mod_82',
 '163030178_mod_0',
 '146682760_mod_97',
 '5312644_mod_0',
 '138454203_mod_0',
 '135002_mod_0',
 '23250',
 '11463588',
 '146682758_mod_26',
 '73242171_mod_0',
 '146682758',
 '146683550_mod_13',
 '75201659',
 '14427323',
 '18676629_mod_3',
 '52921744',
 '146682621_mod_6',
 '52921860',
 '10982228',
 '53813767',
 '74611',
 '95300',
 '123364114',
 '24786700',
 '5282938_mod_0',
 '5282610_mod_0',
 '151922',
 '399_mod_5',
 '5312334_mod_0',
 '76863_mod_0',
 '162875369_mod_1',
 '146683552_mod_89',
 '5288377',
 '138454173_mod_0',
 '5312648_mod_0',
 '163064282_mod_0',
 '5312921_mod_0',
 '129726852_mod_0',
 '138454204',
 '2724554_mod_2',
 '18676629_mod_2',
 '5469810',
 '146682760_mod_36',
 '76518481_mod_0',
 '71402234_mod_0',
 '73721023_mod_0',
 '75009',
 '309_mod_7',
 '10424556',
 '5282787',
 '162900451_mod_2',
 '146683550_mod_0',
 '3632876',
 '146683552_mod_94',
 '5312578',
 '20848956',
 '56935808_mod_0',
 '11701_mod_3',
 '549854',
 '162911315',
 '154212_mod_0',
 '162867002',
 '162927483',
 '85699046',
 '182089',
 '12575964',
 '5282814_mod_0',
 '57494716_mod_0',
 '78360',
 '51439649_mod_10',
 '118343040_mod_2',
 '70_mod_0',
 '5287609_mod_4',
 '73856880',
 '5312669_mod_0',
 '129716173',
 '155301_mod_0',
 '5282457',
 '163057816',
 '53262386',
 '5282650',
 '44203444_mod_0',
 '146683552_mod_103',
 '5282916_mod_0',
 '11036420_mod_0',
 '163088984',
 '56839943',
 '22371595_mod_0',
 '52919352_mod_0',
 '75009_mod_0',
 '5312427',
 '5312781',
 '96020391_mod_1',
 '6439582',
 '145721311_mod_0',
 '138454199',
 '53921228_mod_0',
 '162985202',
 '76312534_mod_0',
 '53262345',
 '5282808',
 '3084276_mod_0',
 '5282595',
 '51439649_mod_13',
 '129819530_mod_0',
 '15157102_mod_0',
 '5287609_mod_13',
 '146683551_mod_103',
 '146682760_mod_19',
 '5282172',
 '91169_mod_0',
 '163020806',
 '146683551_mod_107',
 '12235236_mod_0',
 '5280595_mod_0',
 '56633806',
 '146682758_mod_94',
 '145720652_mod_0',
 '162934221',
 '162979714',
 '971_mod_0',
 '5282773',
 '15569776_mod_0',
 '3035421',
 '146683552_mod_109',
 '5282602_mod_0',
 '5282767_mod_0',
 '195555',
 '163106171_mod_0',
 '5282596',
 '5282875',
 '5470168',
 '12593478',
 '44256492',
 '146683552_mod_69',
 '23427391',
 '102074921_mod_0',
 '5281932',
 '44176401_mod_0',
 '5312640_mod_0',
 '138454216',
 '52921746',
 '71338159',
 '5312691_mod_0',
 '14376443',
 '162953603_mod_0',
 '236484_mod_0',
 '15160959_mod_0',
 '139584015_mod_0',
 '139065_mod_0',
 '57494716',
 '146682760_mod_3',
 '139583621_mod_0',
 '162920802_mod_0',
 '6506600',
 '10924449',
 '5790536_mod_1',
 '52921811_mod_0',
 '5312568_mod_0',
 '5282750',
 '14211733',
 '71442740_mod_0',
 '92033282',
 '52921869_mod_2',
 '162970135',
 '10660115',
 '439766_mod_2',
 '10924204_mod_0',
 '5312919_mod_0',
 '72992343',
 '85699046_mod_0',
 '91856968',
 '5312724',
 '5282880',
 '163012117_mod_0',
 '162985202_mod_1',
 '964_mod_0',
 '5282798_mod_0',
 '134812107',
 '138454211_mod_0',
 '4472903_mod_8',
 '15098254',
 '188958',
 '5281932_mod_10',
 '52921868_mod_1',
 '56935810',
 '5282599_mod_0',
 '163104458_mod_0',
 '85172610_mod_0',
 '440019_mod_1',
 '163071077',
 '5282690_mod_0',
 '18780363_mod_0',
 '146683552_mod_108',
 '118701781_mod_0',
 '399_mod_8',
 '146683550_mod_9',
 '5225199',
 '21656358_mod_1',
 '54350757_mod_0',
 '5312780_mod_0',
 '131839766_mod_0',
 '163037280',
 '162804',
 '136386_mod_2',
 '20842192_mod_1',
 '45480618',
 '138454188',
 '137323807',
 '146682760_mod_67',
 '6419710',
 '139069622_mod_3',
 '65550',
 '5282598',
 '5312645',
 '16061044',
 '14536300',
 '10855782_mod_3',
 '12255551',
 '129725225',
 '181572_mod_0',
 '439887_mod_0',
 '5312306',
 '52921776',
 '54675766_mod_13',
 '5282608',
 '439279',
 '52921734',
 '54280271_mod_0',
 '5312582_mod_0',
 '138454199_mod_0',
 '5460247_mod_11',
 '5280635_mod_1',
 '85128014',
 '152915',
 '45027801',
 '138454210_mod_0',
 '10790',
 '21774056_mod_0',
 '72731335',
 '156013508',
 '5280635_mod_0',
 '10381484_mod_0',
 '92136147',
 '5312928_mod_0',
 '71306366_mod_0',
 '15389270_mod_0',
 '138454176_mod_0',
 '6027',
 '811_mod_0',
 '14325177',
 '5312307',
 '5312572',
 '185666_mod_0',
 '22792275_mod_0',
 '146683551_mod_72',
 '162977695',
 '162872489_mod_0',
 '53769033_mod_0',
 '6440264',
 '54097868',
 '25221579',
 '118701778',
 '18676629_mod_0',
 '444212_mod_6',
 '138454195',
 '162985202_mod_0',
 '5312565',
 '52921815_mod_0',
 '5282670_mod_0',
 '146683552_mod_51',
 '146682620_mod_3',
 '57333876_mod_14',
 '146683551_mod_51',
 '9543668_mod_0',
 '146683552_mod_88',
 '5282877',
 '53262357',
 '9543632_mod_0',
 '10476795',
 '5312323_mod_0',
 '94159_mod_0',
 '5312724_mod_0',
 '78383964',
 '163072910',
 '146683551_mod_50',
 '5312300',
 '5312683',
 '17862689_mod_0',
 '131839777_mod_0',
 '188933',
 '9949348',
 '162974298',
 '5044262',
 '87314906',
 '5773667_mod_0',
 '10722942',
 '165007',
 '4093',
 '53705',
 '44332383_mod_0',
 '146682758_mod_107',
 '5312650_mod_0',
 '14753668_mod_0',
 '146683550_mod_6',
 '54675766_mod_2',
 '5282646',
 '163007378',
 '146682758_mod_0',
 '154674956',
 '162984923',
 '5460291',
 '162852947_mod_0',
 '163010025',
 '138454192',
 '5470168_mod_0',
 '10527725_mod_0',
 '162882588',
 '162927305',
 '5280640_mod_2',
 '49831403',
 '638129_mod_0',
 '57333876_mod_5',
 '21656358_mod_0',
 '52921741_mod_0',
 '5283020',
 '131839778_mod_0',
 '10708201',
 '101929483',
 '5282613_mod_0',
 '5282932_mod_0',
 '5312925_mod_0',
 '5312503',
 '5312568',
 '21656358_mod_8',
 '138454181_mod_0',
 '5312934_mod_0',
 '146683551_mod_37',
 '96020393_mod_2',
 '9543654_mod_1',
 '21774060_mod_0',
 '134812106_mod_0',
 '15157102',
 '129856505',
 '5282888',
 '54678503_mod_3',
 '10731060_mod_0',
 '146682758_mod_25',
 '11036420',
 '139091181',
 '5312779',
 '11686_mod_3',
 '6438690',
 '129695685',
 '5312582',
 '162934219',
 '5282889',
 '156580583',
 '115261',
 '440878',
 '52921732_mod_0',
 '193484',
 '76543222',
 '146682758_mod_97',
 '3378049_mod_0',
 '3931',
 '636783_mod_0',
 '151047',
 '5312349',
 '138454191_mod_0',
 '9543100_mod_2',
 '146683551_mod_32',
 '1899',
 '46906053',
 '52921731',
 '70',
 '146682760_mod_54',
 '146683552_mod_16',
 '5312835_mod_0',
 '13991164',
 '52921776_mod_0',
 '25202225',
 '138454214',
 '14215566_mod_0',
 '5312886',
 '131839779',
 '146682621_mod_0',
 '71716395',
 '146682758_mod_6',
 '163104308',
 '1081_mod_1',
 '5280640_mod_12',
 '5460988_mod_0',
 '5282977_mod_0',
 '522487_mod_0',
 '444212_mod_11',
 '9543610_mod_0',
 '138454185',
 '146683551_mod_22',
 '21656358_mod_14',
 '138454181',
 '5282932',
 '6439582_mod_0',
 '146682758_mod_68',
 '5312502',
 '54678503',
 '146683551_mod_77',
 '136386',
 '146683552_mod_40',
 '129716278_mod_0',
 '118701777',
 '146683552_mod_17',
 '23427118_mod_0',
 '101939806_mod_1',
 '102288',
 '5470167_mod_0',
 '444212_mod_10',
 '146682760_mod_1',
 '5470167',
 '146683552_mod_58',
 '5282919_mod_0',
 '439397',
 '101143233',
 '5322010_mod_2',
 '5282933_mod_0',
 '56935816_mod_0',
 '5312637_mod_0',
 '146683552_mod_76',
 '1081_mod_3',
 '162994789_mod_2',
 '361939_mod_0',
 '12255581',
 '53262333',
 '54585095_mod_0',
 '5282671',
 '67600',
 '96020391_mod_0',
 '53748576_mod_0',
 '146682617',
 '162965206',
 '9543642_mod_0',
 '392323_mod_3',
 '52921735',
 '71330298_mod_0',
 '146683552_mod_13',
 '162875262_mod_0',
 '9543100_mod_1',
 '138756211',
 '5312690',
 '5312569_mod_0',
 '53813767_mod_0',
 '146682760_mod_69',
 '86289860',
 '5282798',
 '5312669',
 '92283',
 '5312947',
 '163048984',
 '71403936_mod_0',
 '5282646_mod_0',
 '5273617',
 '146683550_mod_22',
 '14178794_mod_0',
 '444212_mod_14',
 '5312922_mod_0',
 '14324896_mod_0',
 '75201659_mod_0',
 '4052410_mod_0',
 '5312667',
 '5282822',
 '162924546',
 '5311110',
 '5282747',
 '23651309_mod_2',
 '9543100_mod_3',
 '309_mod_6',
 '146683550_mod_7',
 '53769033',
 '85692_mod_0',
 '10604495',
 '134812121_mod_1',
 '138454209_mod_0',
 '146683550_mod_11',
 '162959938',
 '52921804',
 '90428',
 '15047968',
 '146682758_mod_78',
 '45480554',
 '162896865_mod_0',
 '5280533',
 '456_mod_0',
 '5280640_mod_6',
 '444212_mod_1',
 '56935816',
 '5282814',
 '146683550',
 '125468_mod_0',
 '99459',
 '5282774',
 '16061043_mod_0',
 '68185',
 '11701_mod_0',
 '94236',
 '21773182_mod_0',
 '23427118',
 '75297972',
 '146682621',
 '131751126_mod_0',
 '5282172_mod_0',
 '11347939',
 '5312311_mod_0',
 '52948131',
 '76153820_mod_0',
 '52921733_mod_0',
 '15047965',
 '146682760_mod_24',
 '232555',
 '11483665',
 '444212_mod_2',
 '52921775_mod_0',
 '42607287_mod_0',
 '5282611',
 '52948131_mod_3',
 '146683552_mod_35',
 '44176391',
 '118343040_mod_1',
 '138454170',
 '4169198',
 '163014847',
 '486248',
 '193113',
 '22179045_mod_0',
 '9543658_mod_1',
 '52948131_mod_0',
 '146683552_mod_10',
 '11566680',
 '486248_mod_2',
 '11566977',
 '146683552_mod_30',
 '53635328',
 '146683551_mod_33',
 '76153820',
 '18458_mod_0',
 '188937',
 '162804_mod_0',
 '117384_mod_0',
 '123912',
 '44151232_mod_0',
 '5312694_mod_0',
 '5282703_mod_0',
 '155301',
 '21919_mod_0',
 '5312866_mod_0',
 '53262370_mod_0',
 '138454206',
 '73721020_mod_0',
 '14703945_mod_0',
 '146683550_mod_4',
 '301941_mod_0',
 '5312341',
 '96020391_mod_3',
 '146683552_mod_53',
 '361942',
 '6438157_mod_0',
 '71338159_mod_0',
 '146682760_mod_12',
 '44558968',
 '16061043',
 '439432_mod_0',
 '102376544',
 '5312672_mod_0',
 '156581860',
 '21774061',
 '101170776',
 '154497087',
 '146682758_mod_70',
 '10924204',
 '6442184_mod_3',
 '14325176_mod_0',
 '12358612',
 '138454182',
 '146682758_mod_37',
 '5312646',
 '54029176',
 '16064',
 '3819775_mod_3',
 '146683552_mod_75',
 '67600_mod_0',
 '6440260',
 '9543663_mod_3',
 '52921866_mod_0',
 '19166',
 '157667',
 '399',
 '91860833',
 '101929483_mod_0',
 '163003993_mod_2',
 '146683552_mod_60',
 '5280366',
 '162842972',
 '162900451',
 '99723',
 '5280626_mod_0',
 '6441476_mod_0',
 '440878_mod_0',
 '14703945',
 '146683552_mod_20',
 '138454193_mod_0',
 '52921681_mod_0',
 '52921755_mod_0',
 '146682760_mod_62',
 '54372774',
 '183614',
 '162925759',
 '12723513',
 '85790104',
 '146682621_mod_4',
 '138454196',
 '13245691',
 '162820188',
 '82145_mod_0',
 '91579343',
 '146682760_mod_47',
 '138454207',
 '5312930_mod_0',
 '5312872_mod_0',
 '60204145_mod_1',
 '5287609_mod_3',
 '21774057_mod_0',
 '146682760_mod_82',
 '88768706_mod_0',
 '87266713',
 '71374575_mod_0',
 '5312324_mod_0',
 '301941',
 '71581008',
 '5312955_mod_0',
 '5282922',
 '132551411',
 '5282935',
 '5312926_mod_0',
 '52921818_mod_0',
 '5288266_mod_0',
 '19419923_mod_2',
 '21872_mod_0',
 '16076147',
 '56614806_mod_0',
 '6440904_mod_1',
 '10413881',
 '439432',
 '138454169',
 '5312569',
 '77982',
 '5362565_mod_0',
 '132838897_mod_0',
 '11149122_mod_0',
 '146682620_mod_2',
 '94780',
 '18667409_mod_0',
 '5225199_mod_0',
 '146683551_mod_14',
 '96020391',
 '44203444',
 '146683552_mod_87',
 '18676629',
 '138454197_mod_0',
 '10708201_mod_0',
 '5280640_mod_11',
 '162848753',
 '53438755_mod_0',
 '12304463_mod_2',
 '131839800_mod_0',
 '47',
 '137323808_mod_0',
 '71_mod_0',
 '146501',
 '5312499_mod_0',
 '90472405',
 '16078331_mod_1',
 '138454208_mod_0',
 '21656358_mod_10',
 '146682760_mod_4',
 '298225',
 '643798',
 '12629_mod_4',
 '309_mod_12',
 '14513487_mod_0',
 '91424',
 '52921757',
 '162992535',
 '5312786_mod_0',
 '138454207_mod_0',
 '146682760_mod_18',
 '194014_mod_0',
 '146684601_mod_0',
 '22590170_mod_0',
 '162933172',
 '5281907',
 '188933_mod_3',
 '5280361',
 '146683552_mod_0',
 '5458468_mod_0',
 '11735',
 '16064_mod_0',
 '5460247_mod_1',
 '168447_mod_0',
 '5280635',
 '5287609_mod_10',
 '5312652',
 '42607287',
 '172146_mod_0',
 '15047966_mod_0',
 '309_mod_0',
 '54252776_mod_0',
 '5322010',
 '163006249',
 '12363949',
 '146683551_mod_30',
 '44567090',
 '9543602_mod_0',
 '146682758_mod_61',
 '162940276',
 '5287609_mod_11',
 '5282822_mod_0',
 '146683552_mod_21',
 '146682758_mod_58',
 '146682760_mod_35',
 '162938850',
 '134812122_mod_1',
 '146683552_mod_67',
 '23427391_mod_0',
 '53649065_mod_0',
 '5312723_mod_0',
 '139585909_mod_0',
 '444212_mod_0',
 '6656',
 '5282759',
 '162920407',
 '146682758_mod_38',
 '139588483',
 '12235231_mod_0',
 '118701778_mod_0',
 '5282657_mod_0',
 '41431',
 '5280533_mod_3',
 '21635957_mod_0',
 '73835645',
 '102191387',
 '146683551_mod_54',
 '146683552_mod_36',
 '5214825',
 '5282749',
 '117384',
 '163040349',
 '146682666_mod_0',
 '860',
 '195555_mod_0',
 '86206317_mod_0',
 '182089_mod_0',
 '53262313_mod_0',
 '12400',
 '445929',
 '74076148',
 '5282924',
 '12629_mod_8',
 '6439735_mod_0',
 '5312918_mod_0',
 '163086457',
 '146682758_mod_28',
 '162827285',
 '131839776',
 '439357',
 '118701782_mod_0',
 '101712481_mod_0',
 '5312692',
 '37982_mod_0',
 '10790_mod_0',
 '5312787',
 '52921734_mod_0',
 '10877291',
 '5312642_mod_0',
 '18521421',
 '146683552_mod_49',
 '3496889',
 '146682760_mod_6',
 '16076147_mod_0',
 '146682760_mod_28',
 '9543668_mod_3',
 '24776074',
 '12629',
 '138454209',
 '138756211_mod_0',
 '97917_mod_0',
 '52921775',
 '6478039_mod_0',
 '146682758_mod_75',
 '131839762',
 '5280361_mod_0',
 '20842192_mod_2',
 '5312644',
 '146683551_mod_25',
 '5312673',
 '71341095',
 '5282625_mod_0',
 '5312309',
 '188933_mod_0',
 '146683551_mod_35',
 '56633838',
 '5281932_mod_11',
 '5282996',
 '6438690_mod_0',
 '5282606',
 '73416172_mod_0',
 '5312460',
 '54343379_mod_2',
 '146683550_mod_15',
 '162878943_mod_0',
 '44332383_mod_2',
 '131839782',
 '5312696_mod_0',
 '9543610',
 '10465_mod_0',
 '5312786',
 '134812121_mod_0',
 '57333876_mod_0',
 '134812130',
 '52921750_mod_0',
 '146683551_mod_42',
 '137323808',
 '15389270',
 '146683551_mod_106',
 '146683551_mod_60',
 '5282884',
 '146682760_mod_96',
 '20848956_mod_2',
 '188937_mod_0',
 '139091181_mod_0',
 '146682760_mod_88',
 '12315337',
 '5282907_mod_0',
 '8216',
 '52921867_mod_0',
 '6438485',
 '71_mod_1',
 '54097868_mod_0',
 '146682758_mod_65',
 '6440847_mod_2',
 '146682758_mod_50',
 '5312648',
 '13132095_mod_0',
 '53435999_mod_0',
 '146682621_mod_9',
 '162985202_mod_3',
 '56927872_mod_0',
 '21635957',
 '5312459_mod_0',
 '146683552_mod_81',
 '163106049_mod_0',
 '101972196',
 '162886084',
 '134812109',
 '76152431',
 '131839781',
 '5312637',
 '131133849',
 '6184440',
 '3037595_mod_2',
 '44256510',
 '52921737',
 '5281908_mod_0',
 '146682760_mod_34',
 '5312421',
 '52921751_mod_0',
 '5282915',
 '57333876',
 '146682760_mod_38',
 '73866844',
 '14227575_mod_0',
 '44558967',
 '92033282_mod_0',
 '118343040_mod_0',
 '146682758_mod_103',
 '5282772',
 '146683552_mod_23',
 '54090186',
 '54678503_mod_2',
 '137323811',
 '71374575',
 '53435999',
 '5458468_mod_6',
 '162873327_mod_0',
 '156580583_mod_2',
 '3032811_mod_0',
 '561839',
 '16898',
 '101561582_mod_0',
 '45359277_mod_0',
 '163075458',
 '5312326',
 '21145173',
 '610_mod_0',
 '146683552_mod_91',
 '57294532',
 '6417_mod_0',
 '163033188',
 '522424',
 '5312869_mod_0',
 '162932017_mod_5',
 '5312501_mod_0',
 '1931_mod_0',
 '439766_mod_1',
 '163106049',
 '5312937_mod_0',
 '146682758_mod_100',
 '10660901',
 '52921791_mod_0',
 '188933_mod_1',
 '118701781',
 '5312783_mod_0',
 '56633838_mod_0',
 '90472405_mod_0',
 '5458468_mod_11',
 '10730773',
 '162911871_mod_0',
 '1560',
 '964',
 '71341376',
 '5312819',
 '146682760_mod_77',
 '5312897',
 '56935809_mod_0',
 '146683552_mod_33',
 '85843852_mod_0',
 '134812112',
 '14455_mod_0',
 '5312634',
 '131839799_mod_0',
 '146682758_mod_66',
 '51439649',
 '10556398',
 '127034348',
 '12629_mod_5',
 '16663321_mod_1',
 '399_mod_4',
 '244872_mod_3',
 '440101',
 '146683551_mod_58',
 '440813_mod_3',
 '146683551_mod_71',
 '12311165_mod_0',
 '19597144',
 '5312926',
 '5282649',
 '162899477',
 '5312340',
 '5282922_mod_0',
 '5312923_mod_0',
 '182096',
 '71380416_mod_0',
 '444200',
 '13174986',
 '137323818',
 '5282743',
 '10818083',
 '123957880',
 '92033987',
 '89200762',
 '138454202_mod_0',
 '21575359',
 '146683552_mod_2',
 '5312572_mod_0',
 '445929_mod_0',
 '12723513_mod_0',
 '5469814',
 '146682760_mod_86',
 '5312564_mod_0',
 '5282673',
 '5282603',
 '101972181',
 '52921867',
 '5280732',
 '25244169_mod_0',
 '146683551_mod_3',
 '162925759_mod_0',
 '146682758_mod_62',
 '13915951_mod_0',
 '10730773_mod_0',
 '5282797_mod_0',
 '10347972_mod_0',
 '146683550_mod_14',
 '13991165',
 '9543642',
 ...]

In [160]:
BUL_ids_filtered

['C13750',
 'C20798',
 'C06007',
 'C06099',
 'C16207',
 'C10719',
 'C10586',
 'C07837',
 'C11169',
 'C00437',
 'C21594',
 'C02656_mod_2',
 'C22102',
 'C22141',
 'C01015',
 'C10708',
 'C15117',
 'C12115',
 'C00771',
 'C08885',
 'C10093',
 'C06033',
 'C04081',
 'C21923',
 'C12344',
 'C03843',
 'C15902',
 'C15996',
 'C17747',
 'C19828',
 'C18035',
 'C15579',
 'C10558',
 'C14937',
 'C13103',
 'C07006',
 'C11133',
 'C10350',
 'C20331',
 'C18642',
 'C04615',
 'C14731',
 'C02821',
 'C19409',
 'C00725',
 'C00025_mod_0',
 'C08759',
 'C16526',
 'C15137',
 'C14577',
 'C17146',
 'C20248',
 'C13591',
 'C09326',
 'C09333',
 'C01590',
 'C02457',
 'C08580',
 'C20815',
 'C17827',
 'C17497',
 'C07381',
 'C04644',
 'C14573',
 'C11881',
 'C20947',
 'C18988',
 'C01270',
 'C01279',
 'C18545',
 'C17722',
 'C21580',
 'C14634',
 'C19242',
 'C17107',
 'C09029',
 'C18500',
 'C00250',
 'C15373',
 'C14933',
 'C15168',
 'C11360',
 'C21107',
 'C19164',
 'C07034',
 'C21772',
 'C19482',
 'C01991',
 'C10628',
 'C17837',
 'C11015',
 'C17826',
 'C20365',
 'C00248',
 'C02999',
 'C19539',
 'C18019',
 'C09772',
 'C22200',
 'C14043',
 'C01875',
 'C21569',
 'C19047',
 'C11844',
 'C21517',
 'C15203',
 'C07996',
 'C20624',
 'C04713',
 'C08518',
 'C07711',
 'C15695',
 'C10139',
 'C18568',
 'C00079_mod_0',
 'C09916',
 'C17775',
 'C09753',
 'C13415',
 'C17362',
 'C22012',
 'C08112',
 'C18574',
 'C13858',
 'C01455',
 'C13832',
 'C10912',
 'C10519',
 'C20983',
 'C11584',
 'C00265',
 'C12096',
 'C19991',
 'C05579',
 'C10027',
 'C11265',
 'C00823',
 'C15605',
 'C03764',
 'C05574',
 'C00586',
 'C17382',
 'C19943',
 'C02066',
 'C02389',
 'C11809',
 'C08784',
 'C15293',
 'C08376',
 'C21044',
 'C20717',
 'C12640',
 'C05638',
 'C20994',
 'C05370',
 'C12284',
 'C20010',
 'C01146_mod_0',
 'C06425',
 'C15626',
 'C14671',
 'C07155',
 'C15046',
 'C12307',
 'C20790',
 'C09632',
 'C10819',
 'C03654',
 'C07389',
 'C09021',
 'C17960',
 'C06584',
 'C14446',
 'C11704',
 'C16972',
 'C06825',
 'C20379',
 'C03090',
 'C13494',
 'C17424',
 'C11476',
 'C01133',
 'C12424',
 'C15720',
 'C09739',
 'C08624',
 'C04265',
 'C08865',
 'C00691',
 'C09670',
 'C03943',
 'C00989',
 'C19269',
 'C00431',
 'C13697',
 'C20456',
 'C19783',
 'C09181',
 'C05803',
 'C07966',
 'C10031',
 'C11946',
 'C18070',
 'C01620',
 'C04527',
 'C17524',
 'C12302',
 'C01048',
 'C06239',
 'C21578',
 'C08233',
 'C19878',
 'C19362',
 'C19666',
 'C21613',
 'C08490',
 'C18410',
 'C21423',
 'C07612',
 'C01144',
 'C01438',
 'C11954',
 'C19059',
 'C19535',
 'C02957',
 'C06940',
 'C08968',
 'C10287',
 'C08833',
 'C05435',
 'C11988',
 'C08555',
 'C05706',
 'C15849',
 'C20910',
 'C11507',
 'C11942',
 'C01410',
 'C19916',
 'C10460',
 'C11060',
 'C10107',
 'C07254',
 'C08973',
 'C04535',
 'C12197',
 'C11702',
 'C14637',
 'C01157_mod_0',
 'C20311',
 'C08265',
 'C12155',
 'C08570',
 'C17343',
 'C13813',
 'C09715',
 'C09784',
 'C06599',
 'C05519',
 'C10210',
 'C21849',
 'C19337',
 'C03830',
 'C10046',
 'C14513',
 'C14971',
 'C09498',
 'C11232',
 'C14092',
 'C21217',
 'C22024',
 'C14377',
 'C16737',
 'C00208',
 'C10118',
 'C16196',
 'C05800',
 'C16488',
 'C18719',
 'C14352',
 'C17551',
 'C05695',
 'C22090',
 'C10954',
 'C20844',
 'C02578',
 'C02628',
 'C17902',
 'C09235',
 'C00185',
 'C19260',
 'C09914',
 'C09103',
 'C02264',
 'C20152',
 'C18526',
 'C07138',
 'C09051',
 'C01566',
 'C10524',
 'C02539',
 'C11999',
 'C14957',
 'C07868',
 'C20962',
 'C07336',
 'C06564',
 'C17778',
 'C14411',
 'C06360',
 'C15178',
 'C18094',
 'C01009',
 'C17868',
 'C11740',
 'C07323',
 'C06427_mod_0',
 'C08751',
 'C11685',
 'C20679',
 'C07010',
 'C10814',
 'C18787',
 'C19211',
 'C16771',
 'C08450',
 'C07919',
 'C11305',
 'C20082',
 'C15877',
 'C02778',
 'C06734',
 'C21353',
 'C15360',
 'C11422',
 'C00417_mod_10',
 'C16971',
 'C14382',
 'C00705',
 'C13086',
 'C15128',
 'C16402',
 'C10057',
 'C18499',
 'C14369',
 'C17869',
 'C20189',
 'C18986',
 'C17384',
 'C19369',
 'C08605',
 'C18987',
 'C19890',
 'C11689',
 'C16855',
 'C12327',
 'C14058',
 'C15379',
 'C19415',
 'C10522',
 'C02370',
 'C01951',
 'C00049_mod_1',
 'C20506',
 'C11118',
 'C18091',
 'C03998',
 'C18671',
 'C18226',
 'C21301',
 'C09218',
 'C19082',
 'C03969',
 'C06184',
 'C20460',
 'C15329',
 'C14493',
 'C21248',
 'C08969',
 'C10357',
 'C11583',
 'C00445',
 'C14841',
 'C00366',
 'C04746',
 'C01092',
 'C02363',
 'C11202',
 'C01210',
 'C15342',
 'C11502',
 'C00158_mod_1',
 'C17891',
 'C08509',
 'C16552',
 'C00158_mod_14',
 'C15583',
 'C01404',
 'C02718',
 'C20453',
 'C05376',
 'C09497',
 'C09459',
 'C17394',
 'C03743',
 'C17578',
 'C08831',
 'C18852',
 'C09499',
 'C03629',
 'C11849',
 'C17585',
 'C04300',
 'C18458',
 'C16744',
 'C16556',
 'C07538',
 'C07836',
 'C10319',
 'C17003',
 'C10052',
 'C12317',
 'C00110',
 'C10003',
 'C10077',
 'C11707',
 'C17543',
 'C05434',
 'C14520',
 'C11100',
 'C07125',
 'C00371',
 'C03539',
 'C05802',
 'C03979',
 'C08766',
 'C21057',
 'C16476',
 'C14854',
 'C16954',
 'C19617',
 'C10527',
 'C13827',
 'C20386',
 'C07367',
 'C03927',
 'C16931',
 'C01514',
 'C03981',
 'C08569',
 'C22028',
 'C17491',
 'C21082',
 'C09692',
 'C11308',
 'C22293',
 'C16430',
 'C00158_mod_12',
 'C17730',
 'C10168',
 'C16353',
 'C04559',
 'C05472',
 'C13766',
 'C01746',
 'C11663',
 'C14496',
 'C03963',
 'C06860',
 'C14950',
 'C16570',
 'C05520',
 'C15508',
 'C15103',
 'C19695',
 'C10765',
 'C09548',
 'C16781',
 'C13355',
 'C16597',
 'C01691',
 'C09806',
 'C06654',
 'C06268',
 'C00408_mod_0',
 'C00944',
 'C12366',
 'C19762',
 'C08723',
 'C06893',
 'C20477',
 'C21441',
 'C05011',
 'C06477_mod_0',
 'C06970',
 'C05261',
 'C15188',
 'C03051',
 'C04608',
 'C07771',
 'C17416',
 'C15753',
 'C16783',
 'C09055',
 'C16831',
 'C08898',
 'C16652_mod_0',
 'C19339',
 'C18869',
 'C19385',
 'C15036',
 'C17418',
 'C22013',
 'C20135',
 'C05575',
 'C13364',
 'C05616_mod_0',
 'C17973',
 'C17104',
 'C12433',
 'C21768',
 'C09513',
 'C02627',
 'C08278',
 'C05516',
 'C22055',
 'C11160',
 'C15560',
 'C10573',
 'C17971',
 'C00552',
 'C08114',
 'C21017',
 'C02856',
 'C08602',
 'C08350',
 'C06167',
 'C20217',
 'C05291',
 'C03671',
 'C11116',
 'C01114',
 'C13843',
 'C18735',
 'C10058',
 'C16318',
 'C09375',
 'C14621',
 'C08392',
 'C18448',
 'C20806',
 'C21265',
 'C07376',
 'C06327',
 'C11084',
 'C02549',
 'C13738',
 'C20516',
 'C08211',
 'C09852',
 'C11288',
 'C11322',
 'C07817',
 'C12409',
 'C05339',
 'C18906',
 'C17663',
 'C15139',
 'C15426',
 'C08179',
 'C18809',
 'C19942',
 'C09256',
 'C04318',
 'C17239',
 'C20124',
 'C10617',
 'C09777',
 'C06025_mod_27',
 'C15696',
 'C20700',
 'C06315',
 'C18819',
 'C15684',
 'C01784',
 'C02029',
 'C05847',
 'C11863',
 'C16610',
 'C00302',
 'C21144',
 'C07423',
 'C22164',
 'C12141',
 'C15687',
 'C15942',
 'C21148',
 'C17230',
 'C00894',
 'C14497',
 'C19152',
 'C00011',
 'C06763',
 'C17496',
 'C15047',
 'C05811',
 'C22247',
 'C10575',
 'C22029',
 'C15147',
 'C20174',
 'C18193',
 'C08888',
 'C03677',
 'C16593',
 'C09141',
 'C06689',
 'C13748',
 'C00283',
 'C01230',
 'C19479',
 'C17527',
 'C18791',
 'C20954',
 'C22066',
 'C22173',
 'C02338',
 'C06648',
 'C11131',
 'C17610',
 'C07093',
 'C03070',
 'C14704',
 'C15737',
 'C18108',
 'C15688',
 'C18030',
 'C14944',
 'C10084',
 'C21320',
 'C10590',
 'C20122',
 'C06723',
 'C19120',
 'C17616',
 'C15552',
 'C06952',
 'C20609',
 'C16216',
 'C09354',
 'C09208',
 'C10300',
 'C14710',
 'C15415',
 'C19103',
 'C02197',
 'C15245',
 'C14853',
 'C05382',
 'C16648',
 'C02890',
 'C08302',
 'C06108',
 'C11030',
 'C21354',
 'C10897',
 'C20131',
 'C10996',
 'C17977',
 'C09057',
 'C14919',
 'C14643',
 'C08521',
 'C20270',
 'C01037',
 'C01102',
 'C15719',
 'C09179',
 'C21591',
 'C20050',
 'C00479',
 'C02272',
 'C05464',
 'C10069',
 'C05131',
 'C11282',
 'C17582',
 'C17805',
 'C00402_mod_2',
 'C15617',
 'C11388',
 'C20484',
 'C20344',
 'C22291',
 'C17707',
 'C19619',
 'C18942',
 'C08289',
 'C14990',
 'C06354',
 'C09261',
 'C21401',
 'C15992',
 'C11144',
 'C03646',
 'C01961',
 'C18800',
 'C09581',
 'C07827',
 'C16491',
 'C02835',
 'C04259',
 'C01594',
 'C05643',
 'C09517',
 'C17422',
 'C04932',
 'C08103',
 'C13836',
 'C04628',
 'C19378',
 'C05385',
 'C00386',
 'C14555',
 'C03037',
 'C07026',
 'C17914',
 'C09813',
 'C17056',
 'C20618',
 'C00170',
 'C01267',
 'C10076',
 'C10391',
 'C14181',
 'C08278_mod_3',
 'C11293',
 'C08277_mod_2',
 'C17127',
 'C20158',
 'C09680',
 'C04282',
 'C18552',
 'C19432',
 'C19487',
 'C05086',
 'C10337',
 'C07909',
 'C15028',
 'C15895',
 'C14506',
 'C07092',
 'C12406',
 'C14746',
 'C05773',
 'C00973',
 'C17967',
 'C15328',
 'C15516',
 'C07001',
 'C01346',
 'C21961',
 'C04663',
 'C09128',
 'C18740',
 'C01424_mod_0',
 'C09675',
 'C17894',
 'C05163',
 'C05601_mod_3',
 'C17465',
 'C22085',
 'C14766',
 'C08275',
 'C06748',
 'C15783',
 'C13798',
 'C18237',
 'C17749',
 'C09727',
 'C01732_mod_1',
 'C05551',
 'C10136',
 'C22190',
 'C01621',
 'C14132',
 'C19096',
 'C11687',
 'C04064',
 'C19713',
 'C18755',
 'C19899',
 'C06981',
 'C07235',
 'C10445',
 'C00023',
 'C16996',
 'C18753',
 'C14299',
 'C13629',
 'C00795',
 'C19536',
 'C06902',
 'C02037',
 'C09112',
 'C01467',
 'C16667',
 'C10950',
 'C09805',
 'C18794',
 'C08514',
 'C17210',
 'C14539',
 'C11800',
 'C16374',
 'C22290',
 'C22092',
 'C06721',
 'C16612',
 'C16930',
 'C06852',
 'C09299',
 'C10390',
 'C11483',
 'C14970',
 'C16418',
 'C20468',
 'C16362',
 'C06241',
 'C14481',
 'C17363',
 'C17177',
 'C19601',
 'C07943',
 'C09481',
 'C10712',
 'C19864',
 'C09589',
 'C22222',
 'C14712',
 'C05263',
 'C14376',
 'C19484',
 'C15453',
 'C18699',
 'C18685',
 'C15723',
 'C20853',
 'C03748',
 'C12623',
 'C08634',
 'C19022',
 'C09273',
 'C00123',
 'C05318',
 'C14183',
 'C09511',
 'C06030',
 'C04468',
 'C17071',
 'C05933',
 'C16281',
 'C18769',
 'C20965',
 'C20787',
 'C08342',
 'C08756',
 'C20290',
 'C09363',
 'C10833',
 'C10194',
 'C09436',
 'C11859',
 'C03944',
 'C08241',
 'C01314',
 'C20201',
 'C20882',
 'C19470',
 'C05406',
 'C05965_mod_0',
 'C21664',
 'C04121',
 'C15256',
 'C03693',
 'C11035',
 'C21427',
 'C05795',
 'C14501',
 'C11222',
 'C01518',
 'C16266',
 'C08070',
 'C07231',
 'C06408',
 'C08522',
 'C16905',
 'C19258',
 'C21450',
 'C09372',
 'C12379',
 'C07714',
 'C12525',
 'C17008',
 'C11041',
 'C05648',
 'C09769',
 'C13867',
 'C08872',
 'C01848',
 'C17906',
 'C10743',
 'C16822',
 'C17570',
 'C05610',
 'C20289',
 'C17039',
 'C20023',
 'C21647',
 'C00576',
 'C21218',
 'C13734',
 'C17436',
 'C04808',
 'C11874',
 'C02480',
 'C05598',
 'C11456',
 'C18078',
 'C16311',
 'C06536',
 'C22089',
 'C03928',
 'C01113',
 'C16782',
 'C03656_mod_0',
 'C09231',
 'C08118',
 'C18042',
 'C08381',
 'C11591',
 'C12234',
 'C14216',
 'C13024',
 'C05684',
 'C16321',
 'C12108',
 'C20628',
 'C17796',
 'C09966',
 'C01585_mod_0',
 'C07818',
 'C03739',
 'C10512',
 'C13885',
 'C16167',
 'C00715',
 'C02373',
 'C00511',
 'C16537',
 'C04543',
 'C15955',
 'C14565',
 'C14883',
 'C01033',
 'C22194',
 'C11719',
 'C21436',
 'C06572',
 'C18766',
 'C00498',
 'C21635',
 'C19364',
 'C15088',
 'C09302',
 'C08263',
 'C06544',
 'C08654',
 'C11851',
 'C12531',
 'C08763',
 'C10578',
 'C19221',
 'C19993',
 'C21461',
 'C14747',
 'C02642',
 'C20286',
 'C15990',
 'C01946',
 'C16292',
 'C15193',
 'C15741',
 'C16844',
 'C00632',
 'C12986',
 'C00191',
 'C14772',
 'C00037_mod_0',
 'C08082',
 ...]

In [199]:
len(BUL_ids_filtered)

17073

In [200]:
BUL_ids_filtered_no_mods = [id for id in BUL_ids_filtered if 'mod' not in id]

In [201]:
BUL_ids_filtered_no_mods

['C13750',
 'C20798',
 'C06007',
 'C06099',
 'C16207',
 'C10719',
 'C10586',
 'C07837',
 'C11169',
 'C00437',
 'C21594',
 'C22102',
 'C22141',
 'C01015',
 'C10708',
 'C15117',
 'C12115',
 'C00771',
 'C08885',
 'C10093',
 'C06033',
 'C04081',
 'C21923',
 'C12344',
 'C03843',
 'C15902',
 'C15996',
 'C17747',
 'C19828',
 'C18035',
 'C15579',
 'C10558',
 'C14937',
 'C13103',
 'C07006',
 'C11133',
 'C10350',
 'C20331',
 'C18642',
 'C04615',
 'C14731',
 'C02821',
 'C19409',
 'C00725',
 'C08759',
 'C16526',
 'C15137',
 'C14577',
 'C17146',
 'C20248',
 'C13591',
 'C09326',
 'C09333',
 'C01590',
 'C02457',
 'C08580',
 'C20815',
 'C17827',
 'C17497',
 'C07381',
 'C04644',
 'C14573',
 'C11881',
 'C20947',
 'C18988',
 'C01270',
 'C01279',
 'C18545',
 'C17722',
 'C21580',
 'C14634',
 'C19242',
 'C17107',
 'C09029',
 'C18500',
 'C00250',
 'C15373',
 'C14933',
 'C15168',
 'C11360',
 'C21107',
 'C19164',
 'C07034',
 'C21772',
 'C19482',
 'C01991',
 'C10628',
 'C17837',
 'C11015',
 'C17826',
 'C20365',
 'C00248',
 'C02999',
 'C19539',
 'C18019',
 'C09772',
 'C22200',
 'C14043',
 'C01875',
 'C21569',
 'C19047',
 'C11844',
 'C21517',
 'C15203',
 'C07996',
 'C20624',
 'C04713',
 'C08518',
 'C07711',
 'C15695',
 'C10139',
 'C18568',
 'C09916',
 'C17775',
 'C09753',
 'C13415',
 'C17362',
 'C22012',
 'C08112',
 'C18574',
 'C13858',
 'C01455',
 'C13832',
 'C10912',
 'C10519',
 'C20983',
 'C11584',
 'C00265',
 'C12096',
 'C19991',
 'C05579',
 'C10027',
 'C11265',
 'C00823',
 'C15605',
 'C03764',
 'C05574',
 'C00586',
 'C17382',
 'C19943',
 'C02066',
 'C02389',
 'C11809',
 'C08784',
 'C15293',
 'C08376',
 'C21044',
 'C20717',
 'C12640',
 'C05638',
 'C20994',
 'C05370',
 'C12284',
 'C20010',
 'C06425',
 'C15626',
 'C14671',
 'C07155',
 'C15046',
 'C12307',
 'C20790',
 'C09632',
 'C10819',
 'C03654',
 'C07389',
 'C09021',
 'C17960',
 'C06584',
 'C14446',
 'C11704',
 'C16972',
 'C06825',
 'C20379',
 'C03090',
 'C13494',
 'C17424',
 'C11476',
 'C01133',
 'C12424',
 'C15720',
 'C09739',
 'C08624',
 'C04265',
 'C08865',
 'C00691',
 'C09670',
 'C03943',
 'C00989',
 'C19269',
 'C00431',
 'C13697',
 'C20456',
 'C19783',
 'C09181',
 'C05803',
 'C07966',
 'C10031',
 'C11946',
 'C18070',
 'C01620',
 'C04527',
 'C17524',
 'C12302',
 'C01048',
 'C06239',
 'C21578',
 'C08233',
 'C19878',
 'C19362',
 'C19666',
 'C21613',
 'C08490',
 'C18410',
 'C21423',
 'C07612',
 'C01144',
 'C01438',
 'C11954',
 'C19059',
 'C19535',
 'C02957',
 'C06940',
 'C08968',
 'C10287',
 'C08833',
 'C05435',
 'C11988',
 'C08555',
 'C05706',
 'C15849',
 'C20910',
 'C11507',
 'C11942',
 'C01410',
 'C19916',
 'C10460',
 'C11060',
 'C10107',
 'C07254',
 'C08973',
 'C04535',
 'C12197',
 'C11702',
 'C14637',
 'C20311',
 'C08265',
 'C12155',
 'C08570',
 'C17343',
 'C13813',
 'C09715',
 'C09784',
 'C06599',
 'C05519',
 'C10210',
 'C21849',
 'C19337',
 'C03830',
 'C10046',
 'C14513',
 'C14971',
 'C09498',
 'C11232',
 'C14092',
 'C21217',
 'C22024',
 'C14377',
 'C16737',
 'C00208',
 'C10118',
 'C16196',
 'C05800',
 'C16488',
 'C18719',
 'C14352',
 'C17551',
 'C05695',
 'C22090',
 'C10954',
 'C20844',
 'C02578',
 'C02628',
 'C17902',
 'C09235',
 'C00185',
 'C19260',
 'C09914',
 'C09103',
 'C02264',
 'C20152',
 'C18526',
 'C07138',
 'C09051',
 'C01566',
 'C10524',
 'C02539',
 'C11999',
 'C14957',
 'C07868',
 'C20962',
 'C07336',
 'C06564',
 'C17778',
 'C14411',
 'C06360',
 'C15178',
 'C18094',
 'C01009',
 'C17868',
 'C11740',
 'C07323',
 'C08751',
 'C11685',
 'C20679',
 'C07010',
 'C10814',
 'C18787',
 'C19211',
 'C16771',
 'C08450',
 'C07919',
 'C11305',
 'C20082',
 'C15877',
 'C02778',
 'C06734',
 'C21353',
 'C15360',
 'C11422',
 'C16971',
 'C14382',
 'C00705',
 'C13086',
 'C15128',
 'C16402',
 'C10057',
 'C18499',
 'C14369',
 'C17869',
 'C20189',
 'C18986',
 'C17384',
 'C19369',
 'C08605',
 'C18987',
 'C19890',
 'C11689',
 'C16855',
 'C12327',
 'C14058',
 'C15379',
 'C19415',
 'C10522',
 'C02370',
 'C01951',
 'C20506',
 'C11118',
 'C18091',
 'C03998',
 'C18671',
 'C18226',
 'C21301',
 'C09218',
 'C19082',
 'C03969',
 'C06184',
 'C20460',
 'C15329',
 'C14493',
 'C21248',
 'C08969',
 'C10357',
 'C11583',
 'C00445',
 'C14841',
 'C00366',
 'C04746',
 'C01092',
 'C02363',
 'C11202',
 'C01210',
 'C15342',
 'C11502',
 'C17891',
 'C08509',
 'C16552',
 'C15583',
 'C01404',
 'C02718',
 'C20453',
 'C05376',
 'C09497',
 'C09459',
 'C17394',
 'C03743',
 'C17578',
 'C08831',
 'C18852',
 'C09499',
 'C03629',
 'C11849',
 'C17585',
 'C04300',
 'C18458',
 'C16744',
 'C16556',
 'C07538',
 'C07836',
 'C10319',
 'C17003',
 'C10052',
 'C12317',
 'C00110',
 'C10003',
 'C10077',
 'C11707',
 'C17543',
 'C05434',
 'C14520',
 'C11100',
 'C07125',
 'C00371',
 'C03539',
 'C05802',
 'C03979',
 'C08766',
 'C21057',
 'C16476',
 'C14854',
 'C16954',
 'C19617',
 'C10527',
 'C13827',
 'C20386',
 'C07367',
 'C03927',
 'C16931',
 'C01514',
 'C03981',
 'C08569',
 'C22028',
 'C17491',
 'C21082',
 'C09692',
 'C11308',
 'C22293',
 'C16430',
 'C17730',
 'C10168',
 'C16353',
 'C04559',
 'C05472',
 'C13766',
 'C01746',
 'C11663',
 'C14496',
 'C03963',
 'C06860',
 'C14950',
 'C16570',
 'C05520',
 'C15508',
 'C15103',
 'C19695',
 'C10765',
 'C09548',
 'C16781',
 'C13355',
 'C16597',
 'C01691',
 'C09806',
 'C06654',
 'C06268',
 'C00944',
 'C12366',
 'C19762',
 'C08723',
 'C06893',
 'C20477',
 'C21441',
 'C05011',
 'C06970',
 'C05261',
 'C15188',
 'C03051',
 'C04608',
 'C07771',
 'C17416',
 'C15753',
 'C16783',
 'C09055',
 'C16831',
 'C08898',
 'C19339',
 'C18869',
 'C19385',
 'C15036',
 'C17418',
 'C22013',
 'C20135',
 'C05575',
 'C13364',
 'C17973',
 'C17104',
 'C12433',
 'C21768',
 'C09513',
 'C02627',
 'C08278',
 'C05516',
 'C22055',
 'C11160',
 'C15560',
 'C10573',
 'C17971',
 'C00552',
 'C08114',
 'C21017',
 'C02856',
 'C08602',
 'C08350',
 'C06167',
 'C20217',
 'C05291',
 'C03671',
 'C11116',
 'C01114',
 'C13843',
 'C18735',
 'C10058',
 'C16318',
 'C09375',
 'C14621',
 'C08392',
 'C18448',
 'C20806',
 'C21265',
 'C07376',
 'C06327',
 'C11084',
 'C02549',
 'C13738',
 'C20516',
 'C08211',
 'C09852',
 'C11288',
 'C11322',
 'C07817',
 'C12409',
 'C05339',
 'C18906',
 'C17663',
 'C15139',
 'C15426',
 'C08179',
 'C18809',
 'C19942',
 'C09256',
 'C04318',
 'C17239',
 'C20124',
 'C10617',
 'C09777',
 'C15696',
 'C20700',
 'C06315',
 'C18819',
 'C15684',
 'C01784',
 'C02029',
 'C05847',
 'C11863',
 'C16610',
 'C00302',
 'C21144',
 'C07423',
 'C22164',
 'C12141',
 'C15687',
 'C15942',
 'C21148',
 'C17230',
 'C00894',
 'C14497',
 'C19152',
 'C00011',
 'C06763',
 'C17496',
 'C15047',
 'C05811',
 'C22247',
 'C10575',
 'C22029',
 'C15147',
 'C20174',
 'C18193',
 'C08888',
 'C03677',
 'C16593',
 'C09141',
 'C06689',
 'C13748',
 'C00283',
 'C01230',
 'C19479',
 'C17527',
 'C18791',
 'C20954',
 'C22066',
 'C22173',
 'C02338',
 'C06648',
 'C11131',
 'C17610',
 'C07093',
 'C03070',
 'C14704',
 'C15737',
 'C18108',
 'C15688',
 'C18030',
 'C14944',
 'C10084',
 'C21320',
 'C10590',
 'C20122',
 'C06723',
 'C19120',
 'C17616',
 'C15552',
 'C06952',
 'C20609',
 'C16216',
 'C09354',
 'C09208',
 'C10300',
 'C14710',
 'C15415',
 'C19103',
 'C02197',
 'C15245',
 'C14853',
 'C05382',
 'C16648',
 'C02890',
 'C08302',
 'C06108',
 'C11030',
 'C21354',
 'C10897',
 'C20131',
 'C10996',
 'C17977',
 'C09057',
 'C14919',
 'C14643',
 'C08521',
 'C20270',
 'C01037',
 'C01102',
 'C15719',
 'C09179',
 'C21591',
 'C20050',
 'C00479',
 'C02272',
 'C05464',
 'C10069',
 'C05131',
 'C11282',
 'C17582',
 'C17805',
 'C15617',
 'C11388',
 'C20484',
 'C20344',
 'C22291',
 'C17707',
 'C19619',
 'C18942',
 'C08289',
 'C14990',
 'C06354',
 'C09261',
 'C21401',
 'C15992',
 'C11144',
 'C03646',
 'C01961',
 'C18800',
 'C09581',
 'C07827',
 'C16491',
 'C02835',
 'C04259',
 'C01594',
 'C05643',
 'C09517',
 'C17422',
 'C04932',
 'C08103',
 'C13836',
 'C04628',
 'C19378',
 'C05385',
 'C00386',
 'C14555',
 'C03037',
 'C07026',
 'C17914',
 'C09813',
 'C17056',
 'C20618',
 'C00170',
 'C01267',
 'C10076',
 'C10391',
 'C14181',
 'C11293',
 'C17127',
 'C20158',
 'C09680',
 'C04282',
 'C18552',
 'C19432',
 'C19487',
 'C05086',
 'C10337',
 'C07909',
 'C15028',
 'C15895',
 'C14506',
 'C07092',
 'C12406',
 'C14746',
 'C05773',
 'C00973',
 'C17967',
 'C15328',
 'C15516',
 'C07001',
 'C01346',
 'C21961',
 'C04663',
 'C09128',
 'C18740',
 'C09675',
 'C17894',
 'C05163',
 'C17465',
 'C22085',
 'C14766',
 'C08275',
 'C06748',
 'C15783',
 'C13798',
 'C18237',
 'C17749',
 'C09727',
 'C05551',
 'C10136',
 'C22190',
 'C01621',
 'C14132',
 'C19096',
 'C11687',
 'C04064',
 'C19713',
 'C18755',
 'C19899',
 'C06981',
 'C07235',
 'C10445',
 'C00023',
 'C16996',
 'C18753',
 'C14299',
 'C13629',
 'C00795',
 'C19536',
 'C06902',
 'C02037',
 'C09112',
 'C01467',
 'C16667',
 'C10950',
 'C09805',
 'C18794',
 'C08514',
 'C17210',
 'C14539',
 'C11800',
 'C16374',
 'C22290',
 'C22092',
 'C06721',
 'C16612',
 'C16930',
 'C06852',
 'C09299',
 'C10390',
 'C11483',
 'C14970',
 'C16418',
 'C20468',
 'C16362',
 'C06241',
 'C14481',
 'C17363',
 'C17177',
 'C19601',
 'C07943',
 'C09481',
 'C10712',
 'C19864',
 'C09589',
 'C22222',
 'C14712',
 'C05263',
 'C14376',
 'C19484',
 'C15453',
 'C18699',
 'C18685',
 'C15723',
 'C20853',
 'C03748',
 'C12623',
 'C08634',
 'C19022',
 'C09273',
 'C00123',
 'C05318',
 'C14183',
 'C09511',
 'C06030',
 'C04468',
 'C17071',
 'C05933',
 'C16281',
 'C18769',
 'C20965',
 'C20787',
 'C08342',
 'C08756',
 'C20290',
 'C09363',
 'C10833',
 'C10194',
 'C09436',
 'C11859',
 'C03944',
 'C08241',
 'C01314',
 'C20201',
 'C20882',
 'C19470',
 'C05406',
 'C21664',
 'C04121',
 'C15256',
 'C03693',
 'C11035',
 'C21427',
 'C05795',
 'C14501',
 'C11222',
 'C01518',
 'C16266',
 'C08070',
 'C07231',
 'C06408',
 'C08522',
 'C16905',
 'C19258',
 'C21450',
 'C09372',
 'C12379',
 'C07714',
 'C12525',
 'C17008',
 'C11041',
 'C05648',
 'C09769',
 'C13867',
 'C08872',
 'C01848',
 'C17906',
 'C10743',
 'C16822',
 'C17570',
 'C05610',
 'C20289',
 'C17039',
 'C20023',
 'C21647',
 'C00576',
 'C21218',
 'C13734',
 'C17436',
 'C04808',
 'C11874',
 'C02480',
 'C05598',
 'C11456',
 'C18078',
 'C16311',
 'C06536',
 'C22089',
 'C03928',
 'C01113',
 'C16782',
 'C09231',
 'C08118',
 'C18042',
 'C08381',
 'C11591',
 'C12234',
 'C14216',
 'C13024',
 'C05684',
 'C16321',
 'C12108',
 'C20628',
 'C17796',
 'C09966',
 'C07818',
 'C03739',
 'C10512',
 'C13885',
 'C16167',
 'C00715',
 'C02373',
 'C00511',
 'C16537',
 'C04543',
 'C15955',
 'C14565',
 'C14883',
 'C01033',
 'C22194',
 'C11719',
 'C21436',
 'C06572',
 'C18766',
 'C00498',
 'C21635',
 'C19364',
 'C15088',
 'C09302',
 'C08263',
 'C06544',
 'C08654',
 'C11851',
 'C12531',
 'C08763',
 'C10578',
 'C19221',
 'C19993',
 'C21461',
 'C14747',
 'C02642',
 'C20286',
 'C15990',
 'C01946',
 'C16292',
 'C15193',
 'C15741',
 'C16844',
 'C00632',
 'C12986',
 'C00191',
 'C14772',
 'C08082',
 'C08710',
 'C17744',
 'C10788',
 'C07599',
 'C14128',
 'C08129',
 'C11371',
 'C22231',
 'C05150',
 'C05705',
 'C01935',
 'C15343',
 'C15140',
 'C06917',
 'C15183',
 'C08835',
 'C16995',
 'C08879',
 'C18878',
 'C18598',
 'C14511',
 'C14209',
 'C12849',
 'C17892',
 'C05498',
 'C21978',
 ...]

In [202]:
len(BUL_ids_filtered_no_mods)

16612

In [171]:
BUL_cids_no_mods = [id for id in BUL_cids if 'mod' not in id]

In [203]:
len(BUL_cids_no_mods)

1727

In [178]:
BUL_cids_no_mods

['78383960',
 '5282597',
 '23250',
 '11463588',
 '146682758',
 '75201659',
 '14427323',
 '52921744',
 '52921860',
 '10982228',
 '53813767',
 '74611',
 '95300',
 '123364114',
 '24786700',
 '151922',
 '5288377',
 '138454204',
 '5469810',
 '75009',
 '10424556',
 '5282787',
 '3632876',
 '5312578',
 '20848956',
 '549854',
 '162911315',
 '162867002',
 '162927483',
 '85699046',
 '182089',
 '12575964',
 '78360',
 '73856880',
 '129716173',
 '5282457',
 '163057816',
 '53262386',
 '5282650',
 '163088984',
 '56839943',
 '5312427',
 '5312781',
 '6439582',
 '138454199',
 '162985202',
 '53262345',
 '5282808',
 '5282595',
 '5282172',
 '163020806',
 '56633806',
 '162934221',
 '162979714',
 '5282773',
 '3035421',
 '195555',
 '5282596',
 '5282875',
 '5470168',
 '12593478',
 '44256492',
 '23427391',
 '5281932',
 '138454216',
 '52921746',
 '71338159',
 '14376443',
 '57494716',
 '6506600',
 '10924449',
 '5282750',
 '14211733',
 '92033282',
 '162970135',
 '10660115',
 '72992343',
 '91856968',
 '5312724',
 '5282880',
 '134812107',
 '15098254',
 '188958',
 '56935810',
 '163071077',
 '5225199',
 '163037280',
 '162804',
 '45480618',
 '138454188',
 '137323807',
 '6419710',
 '65550',
 '5282598',
 '5312645',
 '16061044',
 '14536300',
 '12255551',
 '129725225',
 '5312306',
 '52921776',
 '5282608',
 '439279',
 '52921734',
 '85128014',
 '152915',
 '45027801',
 '10790',
 '72731335',
 '156013508',
 '92136147',
 '6027',
 '14325177',
 '5312307',
 '5312572',
 '162977695',
 '6440264',
 '54097868',
 '25221579',
 '118701778',
 '138454195',
 '5312565',
 '5282877',
 '53262357',
 '10476795',
 '78383964',
 '163072910',
 '5312300',
 '5312683',
 '188933',
 '9949348',
 '162974298',
 '5044262',
 '87314906',
 '10722942',
 '165007',
 '4093',
 '53705',
 '5282646',
 '163007378',
 '154674956',
 '162984923',
 '5460291',
 '163010025',
 '138454192',
 '162882588',
 '162927305',
 '49831403',
 '5283020',
 '10708201',
 '101929483',
 '5312503',
 '5312568',
 '15157102',
 '129856505',
 '5282888',
 '11036420',
 '139091181',
 '5312779',
 '6438690',
 '129695685',
 '5312582',
 '162934219',
 '5282889',
 '156580583',
 '115261',
 '440878',
 '193484',
 '76543222',
 '3931',
 '151047',
 '5312349',
 '1899',
 '46906053',
 '52921731',
 '70',
 '13991164',
 '25202225',
 '138454214',
 '5312886',
 '131839779',
 '71716395',
 '163104308',
 '138454185',
 '138454181',
 '5282932',
 '5312502',
 '54678503',
 '136386',
 '118701777',
 '102288',
 '5470167',
 '439397',
 '101143233',
 '12255581',
 '53262333',
 '5282671',
 '67600',
 '146682617',
 '162965206',
 '52921735',
 '138756211',
 '5312690',
 '86289860',
 '5282798',
 '5312669',
 '92283',
 '5312947',
 '163048984',
 '5273617',
 '5312667',
 '5282822',
 '162924546',
 '5311110',
 '5282747',
 '53769033',
 '10604495',
 '162959938',
 '52921804',
 '90428',
 '15047968',
 '45480554',
 '5280533',
 '56935816',
 '5282814',
 '146683550',
 '99459',
 '5282774',
 '68185',
 '94236',
 '23427118',
 '75297972',
 '146682621',
 '11347939',
 '52948131',
 '15047965',
 '232555',
 '11483665',
 '5282611',
 '44176391',
 '138454170',
 '4169198',
 '163014847',
 '486248',
 '193113',
 '11566680',
 '11566977',
 '53635328',
 '76153820',
 '188937',
 '123912',
 '155301',
 '138454206',
 '5312341',
 '361942',
 '44558968',
 '16061043',
 '102376544',
 '156581860',
 '21774061',
 '101170776',
 '154497087',
 '10924204',
 '12358612',
 '138454182',
 '5312646',
 '54029176',
 '16064',
 '6440260',
 '19166',
 '157667',
 '399',
 '91860833',
 '5280366',
 '162842972',
 '162900451',
 '99723',
 '14703945',
 '54372774',
 '183614',
 '162925759',
 '12723513',
 '85790104',
 '138454196',
 '13245691',
 '162820188',
 '91579343',
 '138454207',
 '87266713',
 '301941',
 '71581008',
 '5282922',
 '132551411',
 '5282935',
 '16076147',
 '10413881',
 '439432',
 '138454169',
 '5312569',
 '77982',
 '94780',
 '96020391',
 '44203444',
 '18676629',
 '162848753',
 '47',
 '146501',
 '90472405',
 '298225',
 '643798',
 '91424',
 '52921757',
 '162992535',
 '162933172',
 '5281907',
 '5280361',
 '11735',
 '5280635',
 '5312652',
 '42607287',
 '5322010',
 '163006249',
 '12363949',
 '44567090',
 '162940276',
 '162938850',
 '6656',
 '5282759',
 '162920407',
 '139588483',
 '41431',
 '73835645',
 '102191387',
 '5214825',
 '5282749',
 '117384',
 '163040349',
 '860',
 '12400',
 '445929',
 '74076148',
 '5282924',
 '163086457',
 '162827285',
 '131839776',
 '439357',
 '5312692',
 '5312787',
 '10877291',
 '18521421',
 '3496889',
 '24776074',
 '12629',
 '138454209',
 '52921775',
 '131839762',
 '5312644',
 '5312673',
 '71341095',
 '5312309',
 '56633838',
 '5282996',
 '5282606',
 '5312460',
 '131839782',
 '9543610',
 '5312786',
 '134812130',
 '137323808',
 '15389270',
 '5282884',
 '12315337',
 '8216',
 '6438485',
 '5312648',
 '21635957',
 '101972196',
 '162886084',
 '134812109',
 '76152431',
 '131839781',
 '5312637',
 '131133849',
 '6184440',
 '44256510',
 '52921737',
 '5312421',
 '5282915',
 '57333876',
 '73866844',
 '44558967',
 '5282772',
 '54090186',
 '137323811',
 '71374575',
 '53435999',
 '561839',
 '16898',
 '163075458',
 '5312326',
 '21145173',
 '57294532',
 '163033188',
 '522424',
 '163106049',
 '10660901',
 '118701781',
 '10730773',
 '1560',
 '964',
 '71341376',
 '5312819',
 '5312897',
 '134812112',
 '5312634',
 '51439649',
 '10556398',
 '127034348',
 '440101',
 '19597144',
 '5312926',
 '5282649',
 '162899477',
 '5312340',
 '182096',
 '444200',
 '13174986',
 '137323818',
 '5282743',
 '10818083',
 '123957880',
 '92033987',
 '89200762',
 '21575359',
 '5469814',
 '5282673',
 '5282603',
 '101972181',
 '52921867',
 '5280732',
 '13991165',
 '9543642',
 '439167',
 '5459949',
 '71406001',
 '54706833',
 '76518481',
 '5312561',
 '44606074',
 '131839780',
 '10032287',
 '162907159',
 '145721311',
 '5282695',
 '85142878',
 '5312872',
 '439766',
 '163106171',
 '101719890',
 '5312662',
 '3017884',
 '5282892',
 '92033288',
 '53760237',
 '101221947',
 '162925758',
 '162920802',
 '439885',
 '52921763',
 '52921815',
 '5312657',
 '5312959',
 '9543599',
 '138454215',
 '46176643',
 '131839803',
 '54301927',
 '439871',
 '9543663',
 '439958',
 '46876838',
 '5312670',
 '12311165',
 '53925385',
 '52921727',
 '5312685',
 '123768270',
 '15160959',
 '138454213',
 '54280271',
 '21773677',
 '54486930',
 '10347972',
 '131839796',
 '131231413',
 '52921869',
 '6454051',
 '163104095',
 '14550262',
 '5312547',
 '152802',
 '25172104',
 '5460029',
 '138454211',
 '139590718',
 '52921811',
 '138454174',
 '172146',
 '49831450',
 '10437905',
 '5282599',
 '71343200',
 '52921758',
 '14275216',
 '6439735',
 '139584018',
 '139584015',
 '52921756',
 '5312866',
 '15569774',
 '101713141',
 '52921748',
 '134812121',
 '5282874',
 '5312557',
 '52921766',
 '76312534',
 '5312780',
 '52921733',
 '94485',
 '53685760',
 '162864886',
 '5282878',
 '611552',
 '24740399',
 '44256501',
 '162907522',
 '5282921',
 '5312636',
 '85114799',
 '5282170',
 '23223116',
 '163015445',
 '129726852',
 '13573293',
 '5282993',
 '21774055',
 '9819908',
 '54380165',
 '158957139',
 '101929482',
 '118523814',
 '5282890',
 '656739',
 '162911471',
 '44332383',
 '138454178',
 '5312671',
 '102893',
 '138454177',
 '52921759',
 '131839766',
 '85843852',
 '54294489',
 '52921730',
 '146682616',
 '244872',
 '21872',
 '53262370',
 '162908561',
 '9543654',
 '5312643',
 '3034656',
 '57126169',
 '445994',
 '163016165',
 '324383',
 '11108064',
 '44567089',
 '6442184',
 '10696478',
 '73799287',
 '5287609',
 '11001473',
 '5282901',
 '193736',
 '14215566',
 '163217',
 '53262371',
 '5312612',
 '11019575',
 '11671',
 '139583621',
 '194026',
 '10443517',
 '154212',
 '5312453',
 '10493478',
 '52921854',
 '66308',
 '5312647',
 '5282903',
 '73721021',
 '129819530',
 '5282973',
 '23427167',
 '10465',
 '54725703',
 '5282613',
 '10384193',
 '5312551',
 '71',
 '25242622',
 '5280626',
 '101561582',
 '162878135',
 '90474977',
 '54199934',
 '162964123',
 '134812129',
 '108108',
 '85237375',
 '162877692',
 '5312339',
 '5312956',
 '6421',
 '52921754',
 '163012117',
 '101347591',
 '5312928',
 '162819649',
 '163071722',
 '162915412',
 '5282917',
 '30',
 '163031723',
 '72728218',
 '10606655',
 '44176401',
 '5312932',
 '162850199',
 '6506665',
 '162934863',
 '74426587',
 '53921228',
 '162947490',
 '131839778',
 '5282920',
 '5470165',
 '162878943',
 '5282654',
 '10553995',
 '88470551',
 '439236',
 '119221',
 '85147384',
 '163000852',
 '163016480',
 '71366148',
 '5312297',
 '100936127',
 '146682666',
 '5312782',
 '185666',
 '5312835',
 '5282777',
 '138454203',
 '14354612',
 '52921769',
 '139585778',
 '134812128',
 '44557566',
 '3080745',
 '52921681',
 '5282770',
 '52921750',
 '25156710',
 '52921823',
 '131839763',
 '14034838',
 '5312696',
 '162861993',
 '5282916',
 '52921822',
 '156581863',
 '131839801',
 '15389272',
 '5312313',
 '54104277',
 '25244169',
 '5312654',
 '5282625',
 '53354922',
 '85649667',
 '5312530',
 '342516',
 '163039462',
 '107526',
 '131839760',
 '5365373',
 '135002',
 '9543609',
 '21574240',
 '138454183',
 '162820220',
 '71380416',
 '5282998',
 '52921751',
 '5312322',
 '5312563',
 '14178785',
 '439284',
 '131839799',
 '5312302',
 '162822829',
 '5282607',
 '351388',
 '10462153',
 '45266793',
 '11701',
 '20842192',
 '168447',
 '52921742',
 '22599011',
 '162957117',
 '5282871',
 '52921866',
 '122250',
 '162875369',
 '5312722',
 '85248526',
 '129844165',
 '162885142',
 '361939',
 '21',
 '102316945',
 '118701780',
 '94216',
 '235711',
 '874',
 '5312596',
 '73806731',
 '134812125',
 '5312902',
 '21774057',
 '10073066',
 '101533661',
 '73416172',
 '65127',
 '10473105',
 '12304080',
 '12745',
 '53436588',
 '162891980',
 '52921799',
 '162896865',
 '53955549',
 '19039203',
 '94159',
 '5282602',
 '5470164',
 '53354921',
 '152458',
 '138454210',
 '5312417',
 '22',
 '194024',
 '162866035',
 '5282933',
 '53438755',
 '3083221',
 '129725238',
 '10832498',
 '3014115',
 '5312896',
 '548124',
 '75993194',
 '44575630',
 '439887',
 '71437671',
 '5312935',
 '54260564',
 '162866440',
 '6478040',
 '16039092',
 '396765',
 '72827003',
 '20847505',
 '75049010',
 '12302977',
 '5282609',
 '73242165',
 '15071715',
 '610',
 '3037556',
 '5282778',
 '10429765',
 '2724554',
 '133372',
 '138454190',
 '5312691',
 '54006235',
 '102572138',
 '162974300',
 '5282655',
 '139590623',
 '10980439',
 '23427394',
 '162864516',
 '5282918',
 '5282651',
 '5312649',
 '9543604',
 '162998693',
 '155257',
 '52921806',
 '97917',
 '162995706',
 '5312937',
 '3819775',
 '134812127',
 '5469815',
 '13908548',
 '131839750',
 '11760442',
 '5312816',
 '162947153',
 '5282891',
 '53696786',
 '101143232',
 '23433',
 '20245',
 '14680227',
 '9926753',
 '9543602',
 '23427392',
 '5282632',
 '5282612',
 '162961573',
 '5469812',
 '440019',
 '85610719',
 '5282604',
 '96361162',
 '5312672',
 '5312548',
 '56927872',
 '71343045',
 '5282872',
 '10471679',
 '13916396',
 '9842769',
 '52921768',
 '85050404',
 '69492',
 '101060128',
 '162882811',
 '65032',
 '15931626',
 '456',
 '163074699',
 '52921726',
 '15847269',
 '22207',
 '162924347',
 '5312867',
 '5312901',
 '5312564',
 '6323336',
 '52921752',
 '439710',
 '971',
 '90913450',
 '96020393',
 '162932017',
 '98060850',
 '1931',
 '14284759',
 '5282675',
 '163029223',
 '5282672',
 '21774056',
 '52921740',
 '53262313',
 '162883651',
 '5282697',
 '5312404',
 '71346377',
 '5312952',
 '6992018',
 '162842444',
 '5312651',
 '5312501',
 '22792275',
 '117769',
 '90023152',
 '71343178',
 '14034841',
 '9543632',
 '5312918',
 '10327144',
 '10258781',
 '9974234',
 '5312458',
 '138454172',
 '5790536',
 '52921753',
 '11087559',
 '5312655',
 '9543669',
 '138454167',
 '10468473',
 '146682620',
 '5320340',
 '52921745',
 '21575644',
 '5282601',
 '52921819',
 '5312459',
 '644160',
 '138454173',
 '162857149',
 '53740616',
 '41518',
 '54042050',
 '52921728',
 '10576858',
 '73721022',
 '138454186',
 '54343379',
 '101834247',
 '73721023',
 '10670591',
 '22371595',
 '10352414',
 '5312925',
 '76863',
 '129844282',
 '5282886',
 '5312580',
 '44203446',
 '5312931',
 '71306366',
 '10355900',
 '163030178',
 '126215',
 '137323810',
 '53262368',
 '441476',
 '162886072',
 '5282656',
 '14034839',
 '102296374',
 '3018460',
 '12444451',
 '19737443',
 '21583537',
 '118701779',
 '138454189',
 '58437049',
 '5280595',
 '5312570',
 '11494158',
 '208',
 '10554655',
 '161227',
 '5312894',
 '18780363',
 '139065',
 '131839800',
 '75546',
 '5471014',
 '162937253',
 '444791',
 '5312290',
 '85776164',
 '52921760',
 '185698',
 '129775745',
 '163020051',
 '5462259',
 '22251920',
 '5312343',
 '152909',
 '22179045',
 '70678534',
 '6444276',
 '489938',
 '45359277',
 '138454191',
 '53440328',
 '447347',
 '71410429',
 '102074921',
 '54337467',
 '14502856',
 '24786658',
 '101941234',
 '53748576',
 '54149323',
 ...]

In [180]:
with open('BUL_cids.csv', 'w') as f:
    f.write('CID\n')
    f.write('\n'.join(BUL_cids_no_mods))

In [185]:
df_metanetx_ref_concat = pd.read_csv('metanetx_ref_concat.csv')

In [186]:
df_metanetx_ref_concat

,ID,concat,description
0,BIOMASS,"seed.compound:cpd11416,seedM:M_cpd11416,seedM:...",Biomass
1,MNXM01,"MNXM01,mnx:PMF",PMF||Translocated proton that acccounts for th...
2,MNXM1,"CHEBI:15378,CHEBI:24636,CHEBI:29233,CHEBI:2923...",H+||Hydron||Proton||h||hydrogen ion||proton
3,MNXM10,"CHEBI:16908,CHEBI:57945,bigg.metabolite:nadh,b...",NADH||DPNH||NAD-reduced||NADH+H+||NADH2||Nicot...
4,MNXM100,"CHEBI:17211,CHEBI:58057,SLM:000000305,bigg.met...",geranyl diphosphate
...,...,...,...
42549,MNXM9995,"metacyc.compound:CPD-10654,metacycM:CPD-10654,...",1-chloro-3-methylbenzene||3-chlorotoluene
42550,MNXM99969,envipath:650babc9-9d68-4b73-9332-11972ca26f7b/...,n-pentatriacontane||pentatriacontane
42551,MNXM9999,"CHEBI:84431,chebi:84431,metacyc.compound:CPD-9...","2-heptaprenyl-3-methyl-5-hydroxy-6-methoxy-1,4..."
42552,MNXM99992,"lipidmaps:LMFA07010321,lipidmapsM:LMFA07010321...","(9Z,11E)-tetradeca-9,11-dien-1-yl acetate"
42553,WATER,"CHEBI:15377,CHEBI:29374,CHEBI:29375,CHEBI:3380...",H2O||H20||H3O+||HO-||Hydroxide ion||OH||OH-||W...

In [7]:
df_lotus = pickle_load(f'{DATA_FOLDER}pickles/lotus.pkl')

In [10]:
metanetx_tsv_path = f'{DATA_FOLDER}chem_prop.tsv'
df_metanetx = pd.read_csv(metanetx_tsv_path, sep='\t', header=None, skiprows=353, names=['ID', 'name', 'reference', 'formula', 'charge', 'mass', 'InChI', 'InChIKey', 'SMILES'])

In [11]:
df_metanetx = df_metanetx[df_metanetx['SMILES'].notna()]
df_metanetx = df_metanetx.reset_index(drop=True)

In [12]:
df_metanetx['Molecule'] = df_metanetx.apply(lambda x: Chem.MolFromSmiles(x['SMILES']), axis=1)

RDKit WARNING: [16:36:53] WARNING: not removing hydrogen atom without neighbors
[16:36:53] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:36:53] WARNING: not removing hydrogen atom without neighbors
[16:36:53] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:05] WARNING: not removing hydrogen atom without neighbors
[16:37:05] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:05] WARNING: not removing hydrogen atom without neighbors
[16:37:05] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:06] WARNING: not removing hydrogen atom without neighbors
[16:37:06] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:06] WARNING: not removing hydrogen atom without neighbors
[16:37:06] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:07] WARNING: not removing hydrogen atom without neighbors
[16:37:07] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:13] WARNING: not removing hydrogen atom without neighbors
[16:37:13] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:13] WARNING: not removing hydrogen atom without neighbors
[16:37:13] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:17] WARNING: not removing hydrogen atom without neighbors
[16:37:17] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:17] WARNING: not removing hydrogen atom without neighbors
[16:37:17] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:17] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:17] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:17] WARNING: not removing hydrogen atom without neighbors
[16:37:17] WARNING: not removing hydrogen atom without neighbors
[16:37:17] WARNING: not removing hydrogen atom without neighbors
[16:37:17] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:18] WARNING: not removing hydrogen atom without neighbors
[16:37:18] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:18] WARNING: not removing hydrogen atom without neighbors
[16:37:18] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:35] WARNING: not removing hydrogen atom without neighbors
[16:37:35] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:41] WARNING: not removing hydrogen atom without neighbors
[16:37:41] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:41] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:41] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:41] WARNING: not removing hydrogen atom without neighbors
[16:37:41] WARNING: not removing hydrogen atom without neighbors
[16:37:41] WARNING: not removing hydrogen atom without neighbors
[16:37:41] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:43] WARNING: not removing hydrogen atom without neighbors
[16:37:43] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:44] WARNING: not removing hydrogen atom without neighbors
[16:37:44] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:46] WARNING: not removing hydrogen atom without neighbors
[16:37:46] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:46] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:46] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:46] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:46] WARNING: not removing hydrogen atom without neighbors
[16:37:46] WARNING: not removing hydrogen atom without neighbors
[16:37:46] WARNING: not removing hydrogen atom without neighbors
[16:37:46] WARNING: not removing hydrogen atom without neighbors
[16:37:46] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:37:51] WARNING: not removing hydrogen atom without neighbors
[16:37:51] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:04] WARNING: not removing hydrogen atom without neighbors
[16:38:04] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:04] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:04] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:04] WARNING: not removing hydrogen atom without neighbors
[16:38:04] WARNING: not removing hydrogen atom without neighbors
[16:38:04] WARNING: not removing hydrogen atom without neighbors
[16:38:04] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:04] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:04] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:04] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:04] WARNING: not removing hydrogen atom without neighbors
[16:38:04] WARNING: not removing hydrogen atom without neighbors
[16:38:04] WARNING: not removing hydrogen atom without neighbors
[16:38:04] WARNING: not removing hydrogen atom without neighbors
[16:38:04] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:06] WARNING: not removing hydrogen atom without neighbors
[16:38:06] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:19] WARNING: not removing hydrogen atom without neighbors
[16:38:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:19] WARNING: not removing hydrogen atom without neighbors
[16:38:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:23] WARNING: not removing hydrogen atom without neighbors
[16:38:23] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:40] Conflicting single bond directions around double bond at index 14.
[16:38:40] Conflicting single bond directions around double bond at index 14.
RDKit WARNING: [16:38:40]   BondStereo set to STEREONONE and single bond directions set to NONE.
[16:38:40]   BondStereo set to STEREONONE and single bond directions set to NONE.
RDKit WARNING: [16:38:41] WARNING: not removing hydrogen atom without neighbors
[16:38:41] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:41] WARNING: not removing hydrogen atom without neighbors
[16:38:41] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:41] WARNING: not removing hydrogen atom without neighbors
[16:38:41] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:44] WARNING: not removing hydrogen atom without neighbors
[16:38:44] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:49] WARNING: not removing hydrogen atom without neighbors
[16:38:49] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:50] WARNING: not removing hydrogen atom without neighbors
[16:38:50] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:52] WARNING: not removing hydrogen atom without neighbors
[16:38:52] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:55] WARNING: not removing hydrogen atom without neighbors
[16:38:55] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:38:55] WARNING: not removing hydrogen atom without neighbors
[16:38:55] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:18] WARNING: not removing hydrogen atom without neighbors
[16:39:18] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:18] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:18] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:18] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:18] WARNING: not removing hydrogen atom without neighbors
[16:39:18] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:18] WARNING: not removing hydrogen atom without neighbors
[16:39:18] WARNING: not removing hydrogen atom without neighbors
[16:39:18] WARNING: not removing hydrogen atom without neighbors
[16:39:18] WARNING: not removing hydrogen atom without neighbors
[16:39:18] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
[16:39:19] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
[16:39:20] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors
RDKit WARNING: [16:39:21] WARNING: not removing hydrogen atom without neighbors
[16:39:21] WARNING: not removing hydrogen atom without neighbors

In [13]:
df_metanetx = df_metanetx[['ID', 'SMILES', 'Molecule']]

In [ ]:
# df_metanetx = pickle_load(f'{DATA_FOLDER}pickles/metanetx.pkl')

In [187]:
len(df_metanetx)

1248094

In [188]:
df_metanetx_filtered = df_metanetx[df_metanetx['ID'].isin(df_metanetx_ref_concat['ID'])]

In [189]:
df_metanetx_filtered

,ID,SMILES,Molecule
0,MNXM01,[H+],"<img data-content=""rdkit/molecule"" src=""data:i..."
3,MNXM1,[H+],"<img data-content=""rdkit/molecule"" src=""data:i..."
4,MNXM10,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...,"<img data-content=""rdkit/molecule"" src=""data:i..."
5,MNXM100,CC(C)=CCC/C(C)=C/COP(=O)([O-])OP(=O)([O-])[O-],"<img data-content=""rdkit/molecule"" src=""data:i..."
225,MNXM10002,C=C(C)[C@@H]1CC=C2[C@H](O)CC[C@@H](C)[C@@]2(C)C1,"<img data-content=""rdkit/molecule"" src=""data:i..."
...,...,...,...
1247541,MNXM9995,Cc1cccc(Cl)c1,"<img data-content=""rdkit/molecule"" src=""data:i..."
1247751,MNXM99969,CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC,"<img data-content=""rdkit/molecule"" src=""data:i..."
1247982,MNXM9999,COc1c(O)c(O)c(C)c(C/C=C(\C)CC/C=C(\C)CC/C=C(\C...,"<img data-content=""rdkit/molecule"" src=""data:i..."
1248005,MNXM99992,CC/C=C/C=C\CCCCCCCCOC(C)=O,"<img data-content=""rdkit/molecule"" src=""data:i..."
1248093,WATER,[H]O[H],"<img data-content=""rdkit/molecule"" src=""data:i..."

In [195]:
df_metanetx_filtered = df_metanetx_filtered.reset_index(drop=True)

In [196]:
pickle_dump(f'{DATA_FOLDER}pickles/metanetx_filtered.pkl', df_metanetx_filtered)

In [197]:
df_mtnx_aux = pickle_load(f'{DATA_FOLDER}pickles/metanetx_filtered.pkl')

In [198]:
df_mtnx_aux

,ID,SMILES,Molecule
0,MNXM01,[H+],"<img data-content=""rdkit/molecule"" src=""data:i..."
1,MNXM1,[H+],"<img data-content=""rdkit/molecule"" src=""data:i..."
2,MNXM10,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...,"<img data-content=""rdkit/molecule"" src=""data:i..."
3,MNXM100,CC(C)=CCC/C(C)=C/COP(=O)([O-])OP(=O)([O-])[O-],"<img data-content=""rdkit/molecule"" src=""data:i..."
4,MNXM10002,C=C(C)[C@@H]1CC=C2[C@H](O)CC[C@@H](C)[C@@]2(C)C1,"<img data-content=""rdkit/molecule"" src=""data:i..."
...,...,...,...
27644,MNXM9995,Cc1cccc(Cl)c1,"<img data-content=""rdkit/molecule"" src=""data:i..."
27645,MNXM99969,CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC,"<img data-content=""rdkit/molecule"" src=""data:i..."
27646,MNXM9999,COc1c(O)c(O)c(C)c(C/C=C(\C)CC/C=C(\C)CC/C=C(\C...,"<img data-content=""rdkit/molecule"" src=""data:i..."
27647,MNXM99992,CC/C=C/C=C\CCCCCCCCOC(C)=O,"<img data-content=""rdkit/molecule"" src=""data:i..."
27648,WATER,[H]O[H],"<img data-content=""rdkit/molecule"" src=""data:i..."

In [73]:
with open('metanetx simplified.txt', 'r') as txt_file:
    mnx_ids = txt_file.read()
mnx_ids = mnx_ids.split("\n")
mnx_ids = [mnx_id.replace('@MNXD1', '').replace('@MNXD2', '') for mnx_id in mnx_ids]
mnx_ids = list(set([mnx_id for mnx_id in mnx_ids if mnx_id])) # Get rid of duplicates and empty spaces

In [71]:
df_metanetx_ref = pd.read_csv(f'{DATA_FOLDER}chem_xref.tsv', sep='\t', header=None, skiprows=354, names=['source', 'ID', 'description'])

In [83]:
df_metanetx_ref = df_metanetx_ref[df_metanetx_ref['ID'].isin(mnx_ids)]

In [88]:
ref_ids = df_metanetx_ref['ID'].tolist()
mnx_ids_not_included = [mnx_id for mnx_id in mnx_ids if mnx_id not in ref_ids]

In [89]:
mnx_ids_not_included

[]

In [84]:
len(df_metanetx_ref)

272034

In [115]:
len(mnx_ids)

42554

In [114]:
len(df_metanetx_ref['ID'].unique())

42554

In [126]:
len(df_metanetx_ref)

272034

In [142]:
df_metanetx_bul_filtered = df_metanetx_ref[df_metanetx_ref['source'].str.contains('|'.join(BUL_ids))]

In [137]:
df_metanetx_bul_filtered = df_metanetx_bul_filtered[~df_metanetx_bul_filtered['ID'].str.lower().duplicated()]

In [141]:
len(df_metanetx_bul_filtered)

245871

In [138]:
df_metanetx_bul_filtered

,source,ID,description
53,kegg.compound:C00080,MNXM1,H+||Hydron
128,kegg.compound:C00004,MNXM10,NADH||DPNH||Reduced nicotinamide adenine dinuc...
166,kegg.compound:C00341,MNXM100,Geranyl diphosphate
1552,kegg.compound:C16496,MNXM10006,3-Epiecdysone
2467,kegg.compound:C05834,MNXM10010,3-Methyldioxyindole||3-Hydroxy-3-methyloxindole
...,...,...,...
2992473,kegg.compound:C20838,MNXM9983,"3-[(3aS,4S,7aS)-7a-Methyl-1,5-dioxo-octahydro-..."
2993167,kegg.compound:C06057,MNXM9986,"3-Aminopropane-1,2-diol||(R)-3-Amino-1,2-propa..."
2993414,kegg.compound:C05145,MNXM9987,3-Aminoisobutyric acid||3-Amino-2-methylpropan...
2994130,kegg.compound:C16266,MNXM9990,3-Chloro-2-hydroxymuconic semialdehyde
2996461,kegg.compound:C00001,WATER,H2O||Water

In [149]:
df_metanetx_bul_filtered_final = df_metanetx_ref[~df_metanetx_ref['ID'].isin(df_metanetx_bul_filtered['ID'])]

In [147]:
df_metanetx_bul_filtered_final = [~df_metanetx_bul_filtered_final.isin(df_metanetx_bul_filtered_final['ID'] == 'BIOMASS')]

In [150]:
df_metanetx_bul_filtered_final

,source,ID,description
0,seed.compound:cpd11416,BIOMASS,Biomass
1,seedM:M_cpd11416,BIOMASS,secondary/obsolete/fantasy identifier
2,seedM:cpd11416,BIOMASS,Biomass
3,MNXM01,MNXM01,PMF||Translocated proton that acccounts for th...
4,mnx:PMF,MNXM01,PMF||Translocated proton that acccounts for th...
...,...,...,...
2996240,metacyc.compound:CPD-17804,MNXM99992,"(9Z,11E)-tetradeca-9,11-dien-1-yl acetate"
2996241,metacycM:CPD-17804,MNXM99992,"(9Z,11E)-tetradeca-9,11-dien-1-yl acetate"
2996242,seed.compound:cpd33563,MNXM99992,"(9Z,11E)-tetradeca-9,11-dien-1-yl acetate"
2996243,seedM:M_cpd33563,MNXM99992,secondary/obsolete/fantasy identifier
2996244,seedM:cpd33563,MNXM99992,"(9Z,11E)-tetradeca-9,11-dien-1-yl acetate"

In [122]:
df_metanetx_ref.to_csv('metanetx_ref.csv')

In [102]:
df_metanetx_ref_final = df_metanetx_ref[~df_metanetx_ref['source'].str.lower().str.contains('lipidmaps')]

In [104]:
df_metanetx_ref_final = df_metanetx_ref_final[~df_metanetx_ref_final['source'].str.lower().str.contains('chebi:')]

In [105]:
df_metanetx_ref_final = df_metanetx_ref_final[~df_metanetx_ref_final['source'].str.lower().str.contains('kegg')]

In [107]:
df_metanetx_ref_final = df_metanetx_ref_final[~df_metanetx_ref_final['source'].str.lower().duplicated()]

In [108]:
len(df_metanetx_ref_final)

170634

In [109]:
len(df_metanetx_ref_final[df_metanetx_ref_final['source'].str.lower().str.contains('slm')])

1902

In [110]:
df_metanetx_ref_final.head()

,source,ID,description
0,seed.compound:cpd11416,BIOMASS,Biomass
1,seedM:M_cpd11416,BIOMASS,secondary/obsolete/fantasy identifier
2,seedM:cpd11416,BIOMASS,Biomass
3,MNXM01,MNXM01,PMF||Translocated proton that acccounts for th...
4,mnx:PMF,MNXM01,PMF||Translocated proton that acccounts for th...

In [15]:
len(df_lotus)

276518

In [14]:
len(df_metanetx)

1248094

In [16]:
# Populate compounds ids list with first database (LOTUS)
df_ids = df_lotus.copy()
df_ids.rename({'lotus_id': 'LOTUS_ID'}, axis=1, inplace=True)
df_ids['ID'] = df_ids.index
df_ids['METANETX_ID'] = None
df_ids['PEPTIDE_ID'] = None
df_ids['RHEA_ID'] = None
df_ids['KEGG_ID'] = None
df_ids['LIPIDMAPS_ID'] = None
df_ids['PUBCHEM_ID'] = None

In [17]:
df_ids.head()

,LOTUS_ID,SMILES,Molecule,ID,METANETX_ID,PEPTIDE_ID,RHEA_ID,KEGG_ID,LIPIDMAPS_ID,PUBCHEM_ID
0,LTS0000001,CC(C)CCCCCC=CC=CC(O)=NC(C(O)=NC1CC(O)CCN=C(O)C...,"<img data-content=""rdkit/molecule"" src=""data:i...",0,None,None,None,None,None,None
1,LTS0000002,CC(C)=CC(O)=NCCc1ccc2c(c1)C=CC(C)(C)O2,"<img data-content=""rdkit/molecule"" src=""data:i...",1,None,None,None,None,None,None
2,LTS0000003,CC1(C)CCC2(C(=O)OC3OC(CO)C(O)C(O)C3O)CCC3(C)C(...,"<img data-content=""rdkit/molecule"" src=""data:i...",2,None,None,None,None,None,None
3,LTS0000004,CC(=O)OCC(CC(C)C)N=C(O)C(N=C(O)C1CCCN1C(=O)C(C...,"<img data-content=""rdkit/molecule"" src=""data:i...",3,None,None,None,None,None,None
4,LTS0000005,CC1=C(O)c2c(oc(-c3ccccc3)cc2=O)C(C)(C)C1=O,"<img data-content=""rdkit/molecule"" src=""data:i...",4,None,None,None,None,None,None

In [29]:
df_test = df_ids.iloc[:1000]

In [30]:
len(df_test)

1000

In [31]:
df_test.head()

,LOTUS_ID,SMILES,Molecule,ID,METANETX_ID,PEPTIDE_ID,RHEA_ID,KEGG_ID,LIPIDMAPS_ID,PUBCHEM_ID
0,LTS0000001,CC(C)CCCCCC=CC=CC(O)=NC(C(O)=NC1CC(O)CCN=C(O)C...,"<img data-content=""rdkit/molecule"" src=""data:i...",0,None,None,None,None,None,None
1,LTS0000002,CC(C)=CC(O)=NCCc1ccc2c(c1)C=CC(C)(C)O2,"<img data-content=""rdkit/molecule"" src=""data:i...",1,None,None,None,None,None,None
2,LTS0000003,CC1(C)CCC2(C(=O)OC3OC(CO)C(O)C(O)C3O)CCC3(C)C(...,"<img data-content=""rdkit/molecule"" src=""data:i...",2,None,None,None,None,None,None
3,LTS0000004,CC(=O)OCC(CC(C)C)N=C(O)C(N=C(O)C1CCCN1C(=O)C(C...,"<img data-content=""rdkit/molecule"" src=""data:i...",3,None,None,None,None,None,None
4,LTS0000005,CC1=C(O)c2c(oc(-c3ccccc3)cc2=O)C(C)(C)C1=O,"<img data-content=""rdkit/molecule"" src=""data:i...",4,None,None,None,None,None,None

In [32]:
df_metanetx_test = df_metanetx.iloc[:1000]

In [33]:
len(df_metanetx_test)

1000

In [35]:
df_metanetx_test.head()

,ID,SMILES,Molecule
0,MNXM01,[H+],"<img data-content=""rdkit/molecule"" src=""data:i..."
1,MNXM02,[O-][H],"<img data-content=""rdkit/molecule"" src=""data:i..."
2,MNXM03,[OH3+],"<img data-content=""rdkit/molecule"" src=""data:i..."
3,MNXM1,[H+],"<img data-content=""rdkit/molecule"" src=""data:i..."
4,MNXM10,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...,"<img data-content=""rdkit/molecule"" src=""data:i..."

In [70]:
# vs METANETX
# fp_similarity(fps_total, fps_metanetx, df_metanetx, 'ID', df_ids, 'METANETX_ID')
df_res = fp_similarity_indiv(df_metanetx.iloc[:1], 'ID', df_ids.iloc[:1000], 'METANETX_ID')
df_res

 |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% (0/1)

,LOTUS_ID,SMILES,Molecule,ID,METANETX_ID,PEPTIDE_ID,RHEA_ID,KEGG_ID,LIPIDMAPS_ID,PUBCHEM_ID
0,LTS0000001,CC(C)CCCCCC=CC=CC(O)=NC(C(O)=NC1CC(O)CCN=C(O)C...,"<img data-content=""rdkit/molecule"" src=""data:i...",0,None,None,None,None,None,None
1,LTS0000002,CC(C)=CC(O)=NCCc1ccc2c(c1)C=CC(C)(C)O2,"<img data-content=""rdkit/molecule"" src=""data:i...",1,None,None,None,None,None,None
2,LTS0000003,CC1(C)CCC2(C(=O)OC3OC(CO)C(O)C(O)C3O)CCC3(C)C(...,"<img data-content=""rdkit/molecule"" src=""data:i...",2,None,None,None,None,None,None
3,LTS0000004,CC(=O)OCC(CC(C)C)N=C(O)C(N=C(O)C1CCCN1C(=O)C(C...,"<img data-content=""rdkit/molecule"" src=""data:i...",3,None,None,None,None,None,None
4,LTS0000005,CC1=C(O)c2c(oc(-c3ccccc3)cc2=O)C(C)(C)C1=O,"<img data-content=""rdkit/molecule"" src=""data:i...",4,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...
996,LTS0000997,COC(=O)C12Oc3cccc(O)c3C(=O)C1=CCC(C)C2O,"<img data-content=""rdkit/molecule"" src=""data:i...",996,None,None,None,None,None,None
997,LTS0000998,CC(=O)OC1CCC2(C)C3=C(CCC2C1(C)C)C1(C)CC(=O)C(C...,"<img data-content=""rdkit/molecule"" src=""data:i...",997,None,None,None,None,None,None
998,LTS0000999,Oc1ccc(C=Cc2cc(O)cc3c2C(c2cc(O)cc(O)c2)C(c2ccc...,"<img data-content=""rdkit/molecule"" src=""data:i...",998,None,None,None,None,None,None
999,LTS0001000,Cc1c(O)cc(C(=O)C(O)C2CCC(C)O2)cc1O,"<img data-content=""rdkit/molecule"" src=""data:i...",999,None,None,None,None,None,None
1000,NaN,[H+],"<img data-content=""rdkit/molecule"" src=""data:i...",1000,MNXM01,NaN,NaN,NaN,NaN,NaN

In [61]:
# vs LOTUS
df_res = fp_similarity_indiv(df_ids.iloc[499:500], 'LOTUS_ID', df_ids.iloc[:1000], 'LOTUS_ID')
df_res

 |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% (0/1)

,LOTUS_ID,SMILES,Molecule,ID,METANETX_ID,PEPTIDE_ID,RHEA_ID,KEGG_ID,LIPIDMAPS_ID,PUBCHEM_ID
0,LTS0000001,CC(C)CCCCCC=CC=CC(O)=NC(C(O)=NC1CC(O)CCN=C(O)C...,"<img data-content=""rdkit/molecule"" src=""data:i...",0,None,None,None,None,None,None
1,LTS0000002,CC(C)=CC(O)=NCCc1ccc2c(c1)C=CC(C)(C)O2,"<img data-content=""rdkit/molecule"" src=""data:i...",1,None,None,None,None,None,None
2,LTS0000003,CC1(C)CCC2(C(=O)OC3OC(CO)C(O)C(O)C3O)CCC3(C)C(...,"<img data-content=""rdkit/molecule"" src=""data:i...",2,None,None,None,None,None,None
3,LTS0000004,CC(=O)OCC(CC(C)C)N=C(O)C(N=C(O)C1CCCN1C(=O)C(C...,"<img data-content=""rdkit/molecule"" src=""data:i...",3,None,None,None,None,None,None
4,LTS0000005,CC1=C(O)c2c(oc(-c3ccccc3)cc2=O)C(C)(C)C1=O,"<img data-content=""rdkit/molecule"" src=""data:i...",4,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...
995,LTS0000996,CC(=O)OC1CCC2(C)C(COc3ccc4ccc(=O)oc4c3)C(C)=CC...,"<img data-content=""rdkit/molecule"" src=""data:i...",995,None,None,None,None,None,None
996,LTS0000997,COC(=O)C12Oc3cccc(O)c3C(=O)C1=CCC(C)C2O,"<img data-content=""rdkit/molecule"" src=""data:i...",996,None,None,None,None,None,None
997,LTS0000998,CC(=O)OC1CCC2(C)C3=C(CCC2C1(C)C)C1(C)CC(=O)C(C...,"<img data-content=""rdkit/molecule"" src=""data:i...",997,None,None,None,None,None,None
998,LTS0000999,Oc1ccc(C=Cc2cc(O)cc3c2C(c2cc(O)cc(O)c2)C(c2ccc...,"<img data-content=""rdkit/molecule"" src=""data:i...",998,None,None,None,None,None,None
999,LTS0001000,Cc1c(O)cc(C(=O)C(O)C2CCC(C)O2)cc1O,"<img data-content=""rdkit/molecule"" src=""data:i...",999,None,None,None,None,None,None

In [57]:
df_ids.iloc[1000:1001]

,LOTUS_ID,SMILES,Molecule,ID,METANETX_ID,PEPTIDE_ID,RHEA_ID,KEGG_ID,LIPIDMAPS_ID,PUBCHEM_ID
1000,LTS0001001,CC1CC(O)C2(O)OC3CC4(C)C(CCC5C4CCC4(C)C(C6=CC(=...,"<img data-content=""rdkit/molecule"" src=""data:i...",1000,None,None,None,None,None,None

## Check what KEGG ids are missing in MetanetX dataframe

In [204]:
# Dataframe with MetanetX molecules
df_mtnx_filtered = pickle_load(f'{DATA_FOLDER}pickles/metanetx_filtered.pkl')

In [206]:
# Dataframe with the databases ids linked to each MetanetX id
df_metanetx_ref_concat = pd.read_csv('metanetx_ref_concat.csv')

In [205]:
# Load the BUL (Biological unit library) or Natural products library
with open('data/BUL_names.pkl', 'rb') as f:
    BULnames = pickle.load(f)

BUL_ids = list(set(list(sum(BULnames.keys(), ())))) # Flattened list of current BUL ids
BUL_ids_filtered = [id for id in BUL_ids if id.startswith('C')] # List with only Kegg ids
BUL_ids_filtered_no_mods = [id for id in BUL_ids_filtered if 'mod' not in id] # List with Kegg ids with no mods

In [210]:
# Populate compounds ids list with first database (MetanetX)
df_ids = df_mtnx_filtered.copy()
df_ids.rename({'ID': 'METANETX_ID'}, axis=1, inplace=True)
df_ids['ID'] = df_ids.index
df_ids['LOTUS_ID'] = None
df_ids['PEPTIDE_ID'] = None
df_ids['RHEA_ID'] = None
df_ids['KEGG_ID'] = None
df_ids['LIPIDMAPS_ID'] = None
df_ids['PUBCHEM_ID'] = None

In [221]:
print_progress_bar(0, len(BUL_ids_filtered_no_mods), suffix=f'(0/{len(BUL_ids_filtered_no_mods)})')
for i, BUL_id in enumerate(BUL_ids_filtered_no_mods):
    df_aux = df_metanetx_ref_concat[df_metanetx_ref_concat['concat'].str.contains(BUL_id)]
    if df_aux.empty:
        kegg_mol = next((v for k, v in BULnames.items() if BUL_id in k), None)
        current_kegg_data = {'ID': len(df_ids), 'KEGG_ID': BUL_id, 'Molecule': kegg_mol, 'SMILES': Chem.MolToSmiles(kegg_mol)}
        df_ids = df_ids.append(current_kegg_data, ignore_index=True)
        # print(f'{BUL_id} not found! Inserted.')
    print_progress_bar(i + 1, len(BUL_ids_filtered_no_mods), suffix=f'({i + 1}/{len(BUL_ids_filtered_no_mods)})')

 |████████████████████████████████████████████████████████████████████████████████████████████████████| 100.0% (16612/16612)

In [222]:
df_ids

,METANETX_ID,SMILES,Molecule,ID,LOTUS_ID,PEPTIDE_ID,RHEA_ID,KEGG_ID,LIPIDMAPS_ID,PUBCHEM_ID
0,MNXM01,[H+],"<img data-content=""rdkit/molecule"" src=""data:i...",0,None,None,None,None,None,None
1,MNXM1,[H+],"<img data-content=""rdkit/molecule"" src=""data:i...",1,None,None,None,None,None,None
2,MNXM10,NC(=O)C1=CN([C@@H]2O[C@H](COP(=O)([O-])OP(=O)(...,"<img data-content=""rdkit/molecule"" src=""data:i...",2,None,None,None,None,None,None
3,MNXM100,CC(C)=CCC/C(C)=C/COP(=O)([O-])OP(=O)([O-])[O-],"<img data-content=""rdkit/molecule"" src=""data:i...",3,None,None,None,None,None,None
4,MNXM10002,C=C(C)[C@@H]1CC=C2[C@H](O)CC[C@@H](C)[C@@]2(C)C1,"<img data-content=""rdkit/molecule"" src=""data:i...",4,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...
35669,NaN,C[N+]1([O-])CC[C@]23c4c5ccc(O)c4O[C@H]2[C@@H](...,"<img data-content=""rdkit/molecule"" src=""data:i...",35669,NaN,NaN,NaN,C11786,NaN,NaN
35670,NaN,COc1cc(/C=C/C(=O)OC[C@H]2O[C@@H](Oc3cc4c(cc3O)...,"<img data-content=""rdkit/molecule"" src=""data:i...",35670,NaN,NaN,NaN,C08547,NaN,NaN
35671,NaN,CN1CCN(CCCN2c3ccccc3Sc3ccc(Cl)cc32)CC1,"<img data-content=""rdkit/molecule"" src=""data:i...",35671,NaN,NaN,NaN,C07403,NaN,NaN
35672,NaN,COc1cc(CC2c3c(cc(OC)c(OC)c3OC)CC[N+]2(C)CCCOC(...,"<img data-content=""rdkit/molecule"" src=""data:i...",35672,NaN,NaN,NaN,C07549,NaN,NaN
35673,NaN,C[C@]12CC[C@H]3[C@@H](CCC4=CC(=O)CC[C@@]43C)[C...,"<img data-content=""rdkit/molecule"" src=""data:i...",35673,NaN,NaN,NaN,C14488,NaN,NaN

In [224]:
pickle_dump(f'{DATA_FOLDER}pickles/metanetx+kegg.pkl', df_ids)